const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const contactsHtml = fs.readFileSync(path.join(root,'admin/student_contacts.html'),'utf8');
const contactsJs = fs.readFileSync(path.join(root,'admin/student_contacts.js'),'utf8');
const reviewHtml = fs.readFileSync(path.join(root,'admin/contact_review.html'),'utf8');
const reviewJs = fs.readFileSync(path.join(root,'admin/contact_review.js'),'utf8');
const nav = fs.readFileSync(path.join(root,'admin/nav.js'),'utf8');
const brand = fs.readFileSync(path.join(root,'admin/brand.js'),'utf8');
const worker = fs.readFileSync(path.resolve(root,'../cf-redcake/red-cake-77d5/src/worker.js'),'utf8');
const adminSessionService = fs.readFileSync(path.resolve(root,'../cf-redcake/red-cake-77d5/src/services/admin-session.js'),'utf8');
const gas = fs.readFileSync(path.resolve(root,'../Google Apps Script/clasp-projects/behavioral-endpoint/Code.js'),'utf8');
assert.match(contactsHtml,/data-module="student_contacts"/);
assert.match(contactsJs,/\/admin\/contacts\/student/);
assert.match(contactsJs,/\/admin\/contacts\/suggest/);
assert.match(contactsJs,/publish_suggestion/);
assert.match(reviewHtml,/data-module="contact_review"/);
assert.match(reviewJs,/\/admin\/contacts\/review/);
assert.match(reviewHtml,/id="staffReports"/);
assert.match(reviewJs,/staff_reports/);
assert.match(nav,/key:'student_contacts'/);
assert.match(nav,/key:'contact_review'/);
assert.match(brand,/student_contacts:\s*'Student Contacts'/);
assert.match(worker,/path === "\/admin\/contacts\/student"/);
assert.match(worker,/path === "\/admin\/contacts\/suggest"/);
assert.match(adminSessionService,/student_contacts: true/);
assert.match(adminSessionService,/contact_review: isAdminLike/);
assert.match(gas,/function setupContactHub_\(/);
assert.match(gas,/Contact_Suggestions/);
assert.match(gas,/Contact_Overrides/);
assert.match(gas,/Contact_Consensus/);
assert.match(gas,/Communication_Log/);
assert.match(gas,/PS_Contact_Audit/);
assert.match(gas,/function contactHubRebuildConsensus_\(/);

assert.match(contactsHtml,/communication/i);
assert.match(contactsJs,/\/admin\/communications\/student/);
assert.match(contactsJs,/\/admin\/communications\/create/);
assert.match(worker,/path === "\/admin\/communications\/student"/);
assert.match(worker,/path === "\/admin\/communications\/create"/);
assert.match(adminSessionService,/communication_log: true/);
assert.match(gas,/communication_create/);
assert.match(gas,/communication_list/);
console.log('contact_tools_static.test.js: PASS');
