// EAGLENEST_OUTSIDE_LUNCH_V1 regression for 10-day and class-day policy.
import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateOutsideLunchAttendance } from '../../cf-redcake/red-cake-77d5/src/services/outside-lunch-policy.js';
const days=Array.from({length:10},(_,i)=>`2026-09-${String(i+1).padStart(2,'0')}`);
const daily=(absence={},codes={})=>days.map(date=>({school_date:date,enrolled:1,daily_complete:1,classification:absence[date]||'present',detail_code:codes[date]||absence[date]||'present'}));
const imports=days.map(date=>({school_date:date,complete:1,school_in_session:1,expected_student_meetings:6}));
const meetings=days.map(date=>({school_date:date,expected_count:6,periods_json:JSON.stringify(Array.from({length:6},(_,i)=>({period_local:String(i+1),status:'present'})))}));
test('ten present/on-time days and all on-time classes qualify',()=>{const r=calculateOutsideLunchAttendance(days,daily(),meetings,imports);assert.equal(r.school_met,true);assert.equal(r.arrival_met,true);assert.equal(r.class_met,true);assert.equal(r.class_total,60);});
test('one unexcused absence: school and arrivals pass, excluded from class denominator',()=>{const r=calculateOutsideLunchAttendance(days,daily({[days[0]]:'absent'}),meetings,imports);assert.equal(r.school_present,9);assert.equal(r.school_on_time,9);assert.equal(r.class_total,54);assert.equal(r.school_met,true);assert.equal(r.arrival_met,true);});
test('two unexcused absences fail 9 out of 10 school days',()=>{const r=calculateOutsideLunchAttendance(days,daily({[days[0]]:'absent',[days[1]]:'absent'}),meetings,imports);assert.equal(r.school_present,8);assert.equal(r.school_met,false);assert.equal(r.arrival_met,false);});
test('excused full-day absence counts present/on-time but excludes class denominator',()=>{const r=calculateOutsideLunchAttendance(days,daily({[days[0]]:'absent'},{[days[0]]:'excused_absent'}),meetings,imports);assert.equal(r.school_present,10);assert.equal(r.school_on_time,10);assert.equal(r.class_total,54);});
test('excused school late is still late, not on-time',()=>{const r=calculateOutsideLunchAttendance(days,daily({[days[0]]:'late',[days[1]]:'late'},{[days[0]]:'excused_late',[days[1]]:'late'}),meetings,imports);assert.equal(r.school_met,true);assert.equal(r.arrival_met,false);});
test('5 late classes in 50 classes passes at 90%, 6 fails',()=>{const mk=n=>days.map((date,di)=>({school_date:date,expected_count:5,periods_json:JSON.stringify(Array.from({length:5},(_,i)=>({period_local:String(i+1),status:di*5+i<n?'late':'present'})))}));assert.equal(calculateOutsideLunchAttendance(days,daily(),mk(5),imports).class_met,true);assert.equal(calculateOutsideLunchAttendance(days,daily(),mk(6),imports).class_met,false);});
test('missing official daily records or meeting imports fail closed',()=>{const a=calculateOutsideLunchAttendance(days,daily().slice(1),meetings,imports);assert.equal(a.school_met,false);const b=calculateOutsideLunchAttendance(days,daily(),meetings,imports.slice(1));assert.equal(b.class_met,false);});
test('excused period is treated as on time; excused late is not',()=>{const modified=meetings.map((m,i)=>i!==0?m:({...m,periods_json:JSON.stringify([{period_local:'1',status:'excused'},{period_local:'2',status:'excused_late'},...Array.from({length:4},(_,i)=>({period_local:String(i+3),status:'present'}))])}));const a=calculateOutsideLunchAttendance(days,daily(),modified,imports);assert.equal(a.class_ontime,59);assert.equal(a.class_total,60);assert.equal(a.class_met,true);});
