const API_BASE=(document.querySelector('meta[name="api-base"]')?.content||'').replace(/\/*$/,'')+'/';
const GOOGLE_CLIENT_ID=document.querySelector('meta[name="google-client-id"]')?.content||'';
const SID_KEYS=['ss_admin_session_sid_v1','notifications_admin_session_v1','admin_session_v1','admin_session_sid'];
const SESSION_HEADER='x-admin-session';
const $=(id)=>document.getElementById(id);
let ACCESS=null,DATA=null;

function sid(){try{for(const k of SID_KEYS){const v=String(sessionStorage.getItem(k)||localStorage.getItem(k)||'').trim();if(v)return v}}catch{}return ''}
function stash(r){try{const v=String(r?.headers?.get(SESSION_HEADER)||r?.headers?.get('X-Admin-Session')||'').trim();if(v){for(const k of SID_KEYS){sessionStorage.setItem(k,v);localStorage.setItem(k,v)}}}catch{}}
async function api(path,init={}){const h=new Headers(init.headers||{});const s=sid();if(s)h.set(SESSION_HEADER,s);const r=await fetch(new URL(path,API_BASE),{...init,headers:h,credentials:'include',cache:'no-store'});stash(r);return r}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDate(v){const s=String(v||'').trim();if(!s)return '—';const d=new Date(s.includes('T')?s:s.replace(' ','T'));return Number.isFinite(d.getTime())?d.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):s}
function fmtDuration(sec){const n=Math.max(0,Number(sec||0));if(!n)return '0 sec';const m=Math.floor(n/60),s=Math.round(n%60);return m?`${m}m ${s}s`:`${s}s`}
function directionLabel(v){return v==='incoming'?'Incoming':v==='outgoing'?'Outgoing':v==='internal'?'Internal':'Unknown'}
function contactLabel(m){return [m?.name,m?.relationship].map(v=>String(v||'').trim()).filter(Boolean).join(' • ')||'Matched family contact'}
function studentUrl(m){const u=new URL('./student_view.html',location.href);u.searchParams.set('osis',String(m?.student_number||''));u.searchParams.set('source','calls_dashboard');return u.href}
function localInputValue(v){const s=String(v||'').trim().replace(' ','T');return /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(s)?s.slice(0,16):''}
function communicationUrl(call,m){const u=new URL('./student_contacts.html',location.href);u.searchParams.set('osis',String(m?.student_number||''));if(m?.student_name)u.searchParams.set('name',String(m.student_name));u.searchParams.set('source','phone_dashboard');u.searchParams.set('action','log-communication');if(m?.contact_assoc_id)u.searchParams.set('contact_assoc_id',String(m.contact_assoc_id));u.searchParams.set('comm_method','Phone');u.searchParams.set('comm_direction',call.direction==='incoming'?'Incoming':'Outgoing');u.searchParams.set('category','General');u.searchParams.set('comm_outcome',call.answered?'Spoke/Connected':'No Answer');const at=localInputValue(call.start_local);if(at)u.searchParams.set('comm_at',at);const kind=call.direction==='incoming'?'Incoming':call.direction==='outgoing'?'Outgoing':'Phone';u.searchParams.set('comm_notes',`${kind} phone call${call.campus?` • ${call.campus}`:''} • ${fmtDuration(call.billsec_sec||call.duration_sec)}`);return u.href}
function callRoute(call){if(call.direction==='internal')return `${call.src_label||'Internal extension'} → ${call.dst_label||'Internal extension'}`;const ext=call.direction==='incoming'?(call.dst_label||'School extension'):(call.src_label||'School extension');const contact=call.contact_matches?.[0];const outside=contact?contactLabel(contact):(call.external_phone_last4?`External caller ••••${call.external_phone_last4}`:'External caller');return call.direction==='incoming'?`${outside} → ${ext}`:`${ext} → ${outside}`}
function uniqueStudents(matches){const out=[],seen=new Set();for(const m of matches||[]){const k=String(m?.student_number||'');if(!k||seen.has(k))continue;seen.add(k);out.push(m)}return out}
function render(){const rows=Array.isArray(DATA?.rows)?DATA.rows:[];const q=String($('searchInput').value||'').trim().toLowerCase();const filtered=!q?rows:rows.filter(call=>JSON.stringify({campus:call.campus,src:call.src_label,dst:call.dst_label,last4:call.external_phone_last4,matches:call.contact_matches}).toLowerCase().includes(q));const list=$('callList');if(!filtered.length){list.innerHTML='<div class="panel empty">No calls match this view.</div>';return}list.innerHTML=filtered.map(call=>{const students=uniqueStudents(call.contact_matches);const contactRows=students.map(m=>`<div class="contactRow"><div><div class="contactName">${esc(contactLabel(m))}</div><div class="contactStudent">${esc(m.student_name||m.student_number||'Student')}${m.student_number?` • OSIS ${esc(m.student_number)}`:''}</div></div><div class="rowActions"><a class="btn small" href="${esc(studentUrl(m))}">Open Student</a>${call.direction!=='internal'?`<a class="btn small primary" href="${esc(communicationUrl(call,m))}">Log Communication</a>`:''}</div></div>`).join('');const missed=call.direction==='incoming'&&!call.answered;return `<article class="panel callCard" data-call-key="${esc(call.call_key)}"><div class="callTop"><div><div class="callTitle">${esc(callRoute(call))}</div><div class="callMeta">${esc(fmtDate(call.start_local))} • ${esc(fmtDuration(call.billsec_sec||call.duration_sec))}</div></div><div class="badges"><span class="badge ${esc(call.direction)}">${esc(directionLabel(call.direction))}</span>${call.campus?`<span class="badge">${esc(call.campus)}</span>`:''}${missed?'<span class="badge missed">Missed</span>':''}${call.disposition?`<span class="badge">${esc(call.disposition)}</span>`:''}</div></div><div class="routeLine">${esc(callRoute(call))}</div>${contactRows?`<div class="contactBlock">${contactRows}</div>`:(call.direction!=='internal'?'<div class="callFooter">No Student Contacts match for this external number.</div>':'')}<div class="callFooter">${call.answered?'Answered':'Not answered'}${call.answer_local?` • Answered ${esc(fmtDate(call.answer_local))}`:''}</div></article>`}).join('')}
function renderHeader(){const p=DATA?.preferences||{},bits=[];if(p.scope==='my_extension')bits.push(`My extension ${DATA?.my_extension||''}`);if(p.scope==='campus')bits.push((p.campuses||[]).join(', ')||'Selected campus');if(p.scope==='all')bits.push('All calls');const types=[];if(p.include_internal)types.push('internal');if(p.include_external_incoming)types.push('external incoming');if(p.include_external_outgoing)types.push('external outgoing');$('scopeSummary').textContent=`${bits.join(' • ')}${types.length?` • ${types.join(', ')}`:''}. Change this in My Settings.`;$('viewerPill').textContent=[ACCESS?.email,DATA?.my_extension?`Ext. ${DATA.my_extension}`:''].filter(Boolean).join(' • ');const s=DATA?.summary||{};$('kpiTotal').textContent=Number(s.total||0);$('kpiIncoming').textContent=Number(s.incoming||0);$('kpiOutgoing').textContent=Number(s.outgoing||0);$('kpiInternal').textContent=Number(s.internal||0);$('kpiMissed').textContent=Number(s.missed||0)}
async function load(){$('refreshBtn').disabled=true;$('errorBox').hidden=true;try{const days=$('daysSelect').value||'7';const r=await api(`/admin/calls/list?days=${encodeURIComponent(days)}&limit=300`);const j=await r.json().catch(()=>({}));if(!r.ok||!j?.ok)throw new Error(j?.error||`HTTP ${r.status}`);DATA=j;renderHeader();render()}catch(e){$('errorBox').textContent=e?.message||String(e);$('errorBox').hidden=false;$('callList').innerHTML='<div class="panel empty">Could not load calls.</div>'}finally{$('refreshBtn').disabled=false}}
async function access(){const r=await api('/admin/access');const j=await r.json().catch(()=>null);return r.ok&&j?.ok?j:null}
async function waitGoogle(){for(let i=0;i<160;i++){if(window.google?.accounts?.id)return google.accounts.id;await new Promise(r=>setTimeout(r,50))}throw new Error('Google sign-in failed to load')}
async function login(token){const r=await api('/admin/session/login_google',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({id_token:token}).toString()});const j=await r.json().catch(()=>({}));if(!r.ok||!j?.ok)throw new Error(j?.error||`HTTP ${r.status}`)}
async function boot(){ACCESS=await access();if(!ACCESS){$('loginOut').textContent='Please sign in.';const g=await waitGoogle();g.initialize({client_id:GOOGLE_CLIENT_ID,ux_mode:'popup',callback:async(resp)=>{try{await login(resp.credential);location.reload()}catch(e){$('loginOut').textContent=e?.message||String(e)}}});g.renderButton($('g_id_signin'),{theme:'outline',size:'large'});return}if(!ACCESS?.can?.phone_dashboard)throw new Error('phone_dashboard_extension_required');$('loginCard').hidden=true;$('app').hidden=false;$('refreshBtn').addEventListener('click',load);$('daysSelect').addEventListener('change',load);$('searchInput').addEventListener('input',render);await load()}
boot().catch(e=>{$('loginOut').textContent=e?.message||String(e);$('errorBox').textContent=e?.message||String(e);$('errorBox').hidden=false});
