(() => {
  'use strict';
  const API_BASE = (document.querySelector('meta[name="api-base"]')?.content || '').replace(/\/*$/, '') + '/';
  const CLIENT_ID = document.querySelector('meta[name="google-client-id"]')?.content || '';
  const SID_KEY = 'communications_admin_session_v1';
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
  const fields = ['startDate','endDate','method','category','outcome','direction','grade','followup','actorEmail','studentNumber','source','search','includeDeleted'];
  const fieldToParam = {startDate:'start_date',endDate:'end_date',actorEmail:'actor_email',studentNumber:'student_number',includeDeleted:'include_deleted'};
  let lastQuery = null; let lastCount = 0; let working = false;
  const getSid = () => { try { return String(sessionStorage.getItem(SID_KEY) || localStorage.getItem(SID_KEY) || localStorage.getItem('ss_admin_session_sid_v1') || '').trim(); } catch { return ''; } };
  function saveSid(value) { const sid = String(value || '').trim(); if (!sid) return; try { sessionStorage.setItem(SID_KEY,sid); localStorage.setItem(SID_KEY,sid); localStorage.setItem('ss_admin_session_sid_v1',sid); } catch {} }
  async function api(path, opts = {}) {
    const headers = new Headers(opts.headers || {}); const sid = getSid(); if(sid) headers.set('x-admin-session',sid);
    const response = await fetch(new URL(path,API_BASE), { ...opts, headers, credentials:'include', cache:'no-store' });
    saveSid(response.headers.get('x-admin-session'));
    const data = await response.json().catch(()=>null);
    if(!response.ok || !data?.ok) throw new Error(data?.error || `HTTP ${response.status}`);
    return data;
  }
  function status(value){ $('status').textContent = String(value || ''); }
  function error(value){ $('errorOut').textContent = value || ''; $('errorCard').hidden = !value; }
  function busy(value) { working = value; $('applyBtn').disabled=value; $('clearBtn').disabled=value; $('downloadBtn').disabled=value || !lastQuery || !lastCount; }
  function schoolDate(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const v=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${v.year}-${v.month}-${v.day}`;}
  function defaults(){const today=schoolDate();const y=Number(today.slice(0,4));const m=Number(today.slice(5,7));$('startDate').value=`${m>=7?y:y-1}-07-01`;$('endDate').value=today;for(const id of fields.slice(2))if(id!=='startDate'&&id!=='endDate')$(id).type==='checkbox'?$(id).checked=false:$(id).value='';}
  function params(){const q = new URLSearchParams();for(const id of fields){const el=$(id);const value=el.type==='checkbox'?(el.checked?'1':''):el.value.trim();if(value)q.set(fieldToParam[id]||id,value);}return q;}
  function requireDates(q){const from=q.get('start_date')||'',to=q.get('end_date')||'';if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||to<from)throw new Error('Choose a valid start and end date.');}
  function table(rows){if(!rows.length)return '<div class="empty">No matching records for these filters.</div>';
    return `<table><thead><tr>${['Date','Student','OSIS','Staff','Type / Category','Outcome','Notes','Contact','Follow-up'].map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.school_date||r.contact_at_iso?.slice(0,10))}</td><td>${esc(r.student_name)}</td><td class="mono">${esc(r.student_number)}</td><td>${esc(r.actor_email)}</td><td>${esc(r.method)}<div class="muted small">${esc(r.category)} · ${esc(r.direction)}</div></td><td>${esc(r.outcome)}</td><td>${esc(r.notes)}</td><td>${esc(r.contact_display_name)}<div class="muted small">${esc(r.contact_relationship)}</div></td><td>${r.follow_up_needed?esc(r.follow_up_resolved_at_iso?'Resolved':'Open'):'—'}</td></tr>`).join('')}</tbody></table>`;}
  async function loadFilters(){const data=await api('/admin/communications/export/options');for(const [id,values] of [['method',data.methods],['category',data.categories],['outcome',data.outcomes],['direction',data.directions]]){const select=$(id);for(const value of values||[]){const opt=document.createElement('option');opt.value=String(value);opt.textContent=String(value);select.appendChild(opt);}}}
  async function preview(){if(working)return;error('');lastQuery=null;lastCount=0;busy(true);try{const q=params();requireDates(q);q.set('page','0');status('Searching full communication history…');const data=await api('/admin/communications/export?'+q);lastQuery=params();lastCount=Number(data.count||0);$('count').textContent=lastCount.toLocaleString();$('studentCount').textContent=new Set(data.rows.map(r=>r.student_number)).size.toLocaleString();$('previewCount').textContent=data.rows.length.toLocaleString();$('preview').innerHTML=table(data.rows);$('rangeNote').textContent=`Preview: ${data.rows.length.toLocaleString()} newest of ${lastCount.toLocaleString()} matching communications. CSV includes all matched rows.`;status(`${lastCount.toLocaleString()} matches. ${lastCount?'Ready to download.':'Adjust filters to find communications.'}`);}catch(e){error(`Search failed: ${e.message||e}`);status('Search failed.');$('count').textContent='—';$('studentCount').textContent='—';$('previewCount').textContent='—';$('preview').innerHTML='<div class="empty">Could not retrieve this query.</div>';}finally{busy(false);}}
  const csvFields = [
    ['communication_id','Communication ID'],['school_date','School Date (NY)'],['contact_at_iso','Contact Time (ISO)'],['created_at_iso','Logged Time (ISO)'],
    ['student_number','Student OSIS'],['student_name','Student Name'],['actor_email','Staff Email'],['actor_role','Staff Role'],
    ['method','Method'],['direction','Direction'],['category','Category'],['original_category','Original Category'],['previous_category','Previous Category'],['outcome','Outcome'],
    ['notes','Notes'],['contact_display_name','Contact Name'],['contact_relationship','Relationship'],['contact_phone','Contact Phone'],['contact_email','Contact Email'],
    ['follow_up_needed','Follow-up Needed'],['follow_up_at_iso','Follow-up Due'],['follow_up_owner_email','Follow-up Owner'],['follow_up_resolved_at_iso','Resolved At'],['follow_up_resolved_by_email','Resolved By'],
    ['source','Source'],['related_incident_id','Incident ID'],['import_source','Import Source'],['imported_at_iso','Imported At'],['is_deleted','Deleted'],['deleted_at_iso','Deleted At'],['deleted_by_email','Deleted By'],['delete_reason','Delete Reason']
  ];
  function cell(value){let v = value === true ? 'Yes' : value === false ? 'No' : String(value??'');if(/^[\s\u0000-\u001f]*[=+\-@]/.test(v))v="'"+v;return `"${v.replaceAll('"','""')}"`;}
  async function download(){if(working || !lastQuery || !lastCount)return;error('');busy(true);let rows=[];try{const q=new URLSearchParams(lastQuery);requireDates(q);const pages=Math.ceil(lastCount/250);for(let page=0;page<pages;page++){q.set('page',String(page));if(page===0)q.set('audit_export','1');else q.delete('audit_export');const data=await api('/admin/communications/export?'+q);if(data.count!==lastCount)throw new Error('Records changed during export. Apply filters and try again.');rows.push(...data.rows);status(`Exporting ${rows.length.toLocaleString()} of ${lastCount.toLocaleString()}…`);if(data.rows.length!==Math.min(250,lastCount-page*250))throw new Error('An export page was incomplete; no partial file was saved.');}if(rows.length!==lastCount)throw new Error('Export row count mismatch. No file saved.');const csv='\uFEFF'+csvFields.map(x=>cell(x[1])).join(',')+'\r\n'+rows.map(row=>csvFields.map(x=>cell(row[x[0]])).join(',')).join('\r\n')+'\r\n';const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`EagleNEST_Communications_${q.get('start_date')}_to_${q.get('end_date')}_${lastCount}_records.csv`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status(`Downloaded ${lastCount.toLocaleString()} communications.`);}catch(e){error(`Export failed: ${e.message||e}`);status('Export failed; no partial CSV was saved.');}finally{rows=[];busy(false);}}
  async function bootstrap(){const access=await api('/admin/access');if(!['admin','super_admin'].includes(String(access.role||''))||access.view_as?.active)throw new Error('This export is available only to administrators signed in as themselves.');$('roleTag').textContent=String(access.role).replace('_',' ');$('loginCard').hidden=true;$('app').hidden=false;defaults();try{await loadFilters();}catch(e){error(`Filter options could not load: ${e.message||e}`);}await preview();}
  async function googleLogin(resp){try{$('loginOut').textContent='Signing in…';const j=await api('/admin/session/login_google',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({id_token:resp.credential}).toString()});if(j.sid)saveSid(j.sid);await bootstrap();}catch(e){$('loginOut').textContent=`Sign-in failed: ${e.message||e}`;}}
  async function start(){try{await api('/admin/session/check');await bootstrap();return;}catch{}$('loginCard').hidden=false;$('app').hidden=true;if(!CLIENT_ID){$('loginOut').textContent='Google sign-in is not configured.';return;}try{await new Promise((resolve,reject)=>{let start=Date.now();(function tick(){if(window.google?.accounts?.id)return resolve();if(Date.now()-start>8000)return reject(new Error('Google sign-in failed to load'));setTimeout(tick,50);})();});google.accounts.id.initialize({client_id:CLIENT_ID,callback:googleLogin,ux_mode:'popup',use_fedcm_for_prompt:true});google.accounts.id.renderButton($('g_id_signin'),{theme:'outline',size:'large'});$('loginOut').textContent='Sign in to continue.';}catch(e){$('loginOut').textContent=e.message||String(e);}}
  window.addEventListener('DOMContentLoaded',()=>{$('applyBtn').addEventListener('click',preview);$('downloadBtn').addEventListener('click',download);$('clearBtn').addEventListener('click',()=>{defaults();preview();});for(const id of fields)$(id).addEventListener('change',()=>{$('downloadBtn').disabled=true;lastQuery=null;status('Filters changed — Apply Filters to refresh results.');});start();});
})();
