/* EAGLENEST_DEAN_DASHBOARD_V1 */
(() => {
  'use strict';
  const API_BASE=(()=>{const raw=(document.querySelector('meta[name="api-base"]')?.content||location.origin).trim();try{return new URL(raw).toString().replace(/\/+$/,'/')}catch{return location.origin+'/'}})();
  const HEADER='x-admin-session';
  const $=id=>document.getElementById(id);
  const state={access:null,data:null,outreach:null,selected:null,detail:null,staff:[],scopeConfig:null};
  const TYPES=['Student Check-In','Attendance Conference','Behavior Conference','Restorative Conversation','Re-entry Conference','Family Conference','Behavior Plan Check-In','Reflection/Consequence Follow-Up','Other'];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sid=()=>window.EAGLENEST_AUTH?.getSid?.()||'';
  const setSid=v=>window.EAGLENEST_AUTH?.setSid?.(v);
  async function api(path,init={}){const h=new Headers(init.headers||{});const s=sid();if(s&&!h.has(HEADER))h.set(HEADER,s);const r=await fetch(new URL(path,API_BASE),{...init,headers:h,credentials:'include',cache:'no-store'});const x=r.headers.get(HEADER)||r.headers.get('X-Admin-Session');if(x)setSid(x);const j=await r.json().catch(()=>({}));if(!r.ok||j?.ok===false)throw Object.assign(new Error(j?.message||j?.error||`HTTP ${r.status}`),{payload:j,status:r.status});return j}
  function status(msg,kind=''){$('statusOut').textContent=msg||'';$('statusOut').className=`status ${kind}`.trim()}
  function fmtPct(v){return v===null||v===undefined?'—':`${Number(v).toFixed(Number(v)%1?1:0)}%`}
  function fmtDate(v){if(!v)return'—';const d=new Date(v.includes('T')?v:`${v}T12:00:00`);return Number.isFinite(d.getTime())?d.toLocaleDateString():v}
  function fmtWhen(v){if(!v)return'—';const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString():v}
  function localDateTime(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
  function plusDays(days){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
  function query(){const p=new URLSearchParams({preset:$('preset').value});if($('preset').value==='custom'){p.set('start',$('startDate').value);p.set('end',$('endDate').value)}return p}
  function focusMatch(row,focus){if(!focus)return true;return (row.reasons||[]).some(r=>r.key===focus||(focus==='attendance'&&['attendance','attendance_today'].includes(r.key))||(focus==='followup'&&['followup','overdue_followup'].includes(r.key)))}
  function filteredQueue(){const q=$('searchInput').value.trim().toLowerCase(),grade=$('gradeFilter').value,focus=$('focusFilter').value,source=q?(state.data?.students||[]):(state.data?.queue||[]);return source.filter(r=>(!grade||r.grade===grade)&&(!q||`${r.name} ${r.osis}`.toLowerCase().includes(q))&&focusMatch(r,focus))}
  function renderScope(){const s=state.data?.scope||{};if(!s.configured){$('scopeText').textContent='No Dean assignment configured for this account.';return}const bits=s.schoolwide?['Schoolwide Super Admin view']:[s.grades?.length?`Grades ${s.grades.join(', ')}`:'No grade assignment',s.explicit_students?.length?`${s.explicit_students.length} individually assigned student${s.explicit_students.length===1?'':'s'}`:''];$('scopeText').textContent=`${bits.filter(Boolean).join(' · ')} · ${s.student_count||0} students`;}
  function renderKpis(){const s=state.data?.summary||{};const cards=[['Students requiring attention',s.priority_students],['Needs outreach today',s.today_outreach],['Attendance concerns',s.attendance_below_target],['Behavior events',s.behavior_events],['Open incidents',s.open_incidents],['Active MTSS',s.active_mtss],['Overdue follow-ups',s.overdue_followups],['ISS today',s.iss],['OSS today',s.oss]];$('kpis').innerHTML=cards.map(([l,v])=>`<div class="kpi"><span>${esc(l)}</span><strong>${Number(v||0)}</strong></div>`).join('')}
  function renderQueue(){const rows=filteredQueue();$('queueCount').textContent=`${rows.length} shown`;$('queue').innerHTML=rows.length?rows.map(r=>`<article class="studentCard" data-osis="${esc(r.osis)}"><div class="studentTop"><div><div class="studentName">${esc(r.name)}</div><div class="meta">Grade ${esc(r.grade||'—')} · OSIS ${esc(r.osis)}</div></div>${r.suspension?.effective_status?`<span class="pill danger">${esc(String(r.suspension.effective_status).toUpperCase())}</span>`:''}</div><div class="tags">${(r.reasons||[]).map(x=>`<span class="pill ${x.key==='overdue_followup'||x.key==='incident'?'danger':x.key==='attendance'||x.key==='mtss'?'warn':''}">${esc(x.label)}</span>`).join('')}</div><div class="metrics"><span>Daily: <strong>${fmtPct(r.attendance?.daily?.percentage)}</strong></span><span>Meeting on-time: <strong>${fmtPct(r.attendance?.meeting?.percentage)}</strong></span><span>Behavior logs: <strong>${Number(r.behavior_count||0)}</strong></span><span>Open incidents: <strong>${Number(r.open_incident_count||0)}</strong></span></div></article>`).join(''):'<div class="empty">No students match these filters.</div>';$('queue').querySelectorAll('[data-osis]').forEach(el=>el.addEventListener('click',()=>openStudent(el.dataset.osis)));}
  function renderFollowups(){const today=state.data?.today||new Date().toISOString().slice(0,10),rows=(state.data?.interventions||[]).filter(x=>x.follow_up_status==='open').sort((a,b)=>String(a.follow_up_due_date).localeCompare(String(b.follow_up_due_date)));$('followups').innerHTML=rows.length?rows.map(x=>`<div class="listItem"><button class="linkBtn" data-follow-student="${esc(x.student_number)}"><strong>${esc(x.student_name||x.student_number)}</strong></button><div class="meta">${esc(x.intervention_type)} · due ${esc(fmtDate(x.follow_up_due_date))}</div>${x.follow_up_due_date&&x.follow_up_due_date<today?'<span class="pill danger">Overdue</span>':'<span class="pill warn">Open</span>'}</div>`).join(''):'<div class="empty">No open Dean follow-ups.</div>';$('followups').querySelectorAll('[data-follow-student]').forEach(b=>b.addEventListener('click',()=>openStudent(b.dataset.followStudent)));}
  function renderGrades(){const current=$('gradeFilter').value,grades=[...new Set((state.data?.students||[]).map(x=>x.grade).filter(Boolean))].sort((a,b)=>Number(a)-Number(b));$('gradeFilter').innerHTML='<option value="">All scoped grades</option>'+grades.map(g=>`<option value="${esc(g)}">Grade ${esc(g)}</option>`).join('');if(grades.includes(current))$('gradeFilter').value=current}
  function render(){renderScope();renderKpis();renderGrades();renderQueue();renderFollowups();$('practiceBanner').hidden=state.data?.practice!==true;$('manageScopeBtn').hidden=state.access?.can?.super_admin!==true;const w=state.data?.window;if(w)status(`${w.label} · ${w.start} to ${w.end}${state.data?.powerschool_status_available===false?' · PowerSchool suspension status unavailable':''}`,state.data?.powerschool_status_available===false?'error':'')}
  function mergeTodayOutreach(j,outreach){if(!j?.students?.length||!outreach?.rows)return;const by=new Map(j.students.map(x=>[String(x.osis),x]));let count=0;for(const o of outreach.rows){const r=by.get(String(o.osis||''));if(!r)continue;r.today_outreach=o;if(['needs_call','needs_verification'].includes(o.status)){count++;if(!(r.reasons||[]).some(x=>x.key==='attendance_today'))(r.reasons??=[]).unshift({key:'attendance_today',label:o.status==='needs_call'?'Attendance outreach today':'Verify campus presence today'});r.needs_attention=true;}}j.queue=j.students.filter(x=>x.needs_attention);j.summary=j.summary||{};j.summary.today_outreach=count;j.summary.priority_students=j.queue.length;}
  async function load(){status('Loading Dean dashboard…');const [j,outreach]=await Promise.all([api(`/admin/dean/dashboard?${query().toString()}`),api('/admin/attendance_outreach').catch(()=>null)]);state.outreach=outreach;mergeTodayOutreach(j,outreach);state.data=j;render();}
  function detailRow(title,meta='',body=''){return `<div class="detailRow"><strong>${esc(title)}</strong>${meta?`<div class="meta">${esc(meta)}</div>`:''}${body?`<div>${esc(body)}</div>`:''}</div>`}
  function renderStudent(){const d=state.detail,s=d.student||{},a=d.attendance?.attendance||{},daily=a.daily_attendance_requirement||{},meet=a.on_time_class_requirement||{};$('studentTitle').textContent=s.name||s.osis||'Student';$('studentMeta').textContent=`Grade ${s.grade||'—'} · OSIS ${s.osis||state.selected}`;$('studentStats').innerHTML=[`Daily ${fmtPct(daily.percentage)}`,`Meeting on-time ${fmtPct(meet.percentage)}`,`${d.behaviors?.length||0} behavior logs`,`${d.incidents?.filter(x=>!['resolved','closed','complete','completed'].includes(String(x.status||'').toLowerCase())).length||0} open incidents`,`${d.mtss_cases?.length||0} active MTSS`,d.suspension?.effective_status?String(d.suspension.effective_status).toUpperCase():null].filter(Boolean).map(x=>`<span class="pill">${esc(x)}</span>`).join('');
    const dailyRows=d.attendance?.daily_rows||[],todayOutreach=(state.data?.students||[]).find(x=>x.osis===state.selected)?.today_outreach||null;$('attendanceDetail').innerHTML=(todayOutreach?detailRow('Today',`Outreach status: ${todayOutreach.status||'—'} · Current location: ${todayOutreach.current_location||'—'}`,todayOutreach.latest_attendance_communication?'Family contact already logged':''):'' )+(dailyRows.slice(0,10).map(x=>detailRow(fmtDate(x.school_date),`${x.classification||'—'}${x.detail_code?` · ${x.detail_code}`:''}`,x.source||'')).join(''))||'<div class="empty">No attendance rows in this window.</div>';
    const behavior=(d.behaviors||[]).slice(0,12).map(x=>detailRow(x.event_label||x.event_key,`${fmtWhen(x.occurred_at_iso)} · ${x.room||'—'} · ${x.actor_email||''}`,x.notes||''));const incidents=(d.incidents||[]).slice(0,8).map(x=>detailRow(`Incident ${x.incident_id} · ${x.status||'New'}`,`${fmtDate(x.incident_date)} · ${x.category||x.location_category||'Incident'}`,x.description||''));$('behaviorDetail').innerHTML=[...behavior,...incidents].join('')||'<div class="empty">No behavior or incident records in view.</div>';
    const mtss=(d.mtss_cases||[]).map(x=>detailRow(`Tier ${x.tier} ${x.domain} MTSS · ${x.status}`,`Next review ${fmtDate(x.next_review_date)} · Owner ${x.owner_email||'unassigned'}`,x.reason||x.title||''));if(d.suspension?.effective_status)mtss.unshift(detailRow(`${String(d.suspension.effective_status).toUpperCase()} today`,d.suspension.powerschool_confirmed?'Confirmed in PowerSchool':'Pending PowerSchool entry',d.suspension.manual?.note||''));$('supportDetail').innerHTML=mtss.join('')||'<div class="empty">No active attendance/behavior MTSS or suspension status.</div>';
    const ints=d.interventions||[];$('deanTimeline').innerHTML=ints.length?ints.map(x=>`<div class="detailRow"><strong>${esc(x.intervention_type)}</strong><div class="meta">${esc(fmtWhen(x.occurred_at_iso))} · ${esc(x.domain)} · ${esc(x.created_by_email)}</div><div>${esc(x.note_text)}</div>${x.follow_up_status==='open'?`<div class="toolbar" style="margin-top:8px"><span class="pill ${x.follow_up_due_date<d.today?'danger':'warn'}">Follow-up due ${esc(fmtDate(x.follow_up_due_date))}</span><button data-resolve="${esc(x.intervention_id)}">Resolve</button></div>`:x.follow_up_status==='resolved'?'<span class="pill good">Follow-up resolved</span>':''}</div>`).join(''):'<div class="empty">No Dean interventions yet.</div>';$('deanTimeline').querySelectorAll('[data-resolve]').forEach(b=>b.addEventListener('click',()=>resolveFollowup(b.dataset.resolve)));}
  async function openStudent(osis){state.selected=osis;$('studentPanel').hidden=false;status('Loading student…');const j=await api(`/admin/dean/student?osis=${encodeURIComponent(osis)}&${query().toString()}`);state.detail=j;renderStudent();$('studentPanel').scrollIntoView({behavior:'smooth',block:'start'});status('')}
  async function resolveFollowup(id){if(!confirm('Mark this Dean follow-up resolved?'))return;await api('/admin/dean/followup/resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({intervention_id:id,resolved:true})});await Promise.all([openStudent(state.selected),load()])}
  function openIntervention(){$('interventionStudent').textContent=`${state.detail?.student?.name||state.selected} · ${state.selected}`;$('intType').innerHTML=TYPES.map(x=>`<option>${esc(x)}</option>`).join('');$('intWhen').value=localDateTime();$('intNote').value='';$('intFollow').checked=false;$('intDue').value=plusDays(7);$('intDueWrap').hidden=true;$('intStatus').textContent='';$('interventionModal').hidden=false;$('intNote').focus()}
  async function saveIntervention(){const follow=$('intFollow').checked,payload={student_number:state.selected,domain:$('intDomain').value,intervention_type:$('intType').value,occurred_at_iso:new Date($('intWhen').value).toISOString(),note_text:$('intNote').value.trim(),follow_up_needed:follow,follow_up_due_date:follow?$('intDue').value:''};$('saveInterventionBtn').disabled=true;try{await api('/admin/dean/intervention',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});$('interventionModal').hidden=true;await Promise.all([openStudent(state.selected),load()])}catch(e){$('intStatus').textContent=`Could not save: ${e.message}`}finally{$('saveInterventionBtn').disabled=false}}
  function scopeAssignments(){return state.scopeConfig?.deans||{}}
  function renderScopeList(){const rows=Object.values(scopeAssignments()).sort((a,b)=>a.email.localeCompare(b.email));const names=new Map(state.staff.map(x=>[String(x.email||'').toLowerCase(),x.name||x.email]));$('scopeList').innerHTML=rows.length?rows.map(x=>`<div class="scopeAssignment"><div><strong>${esc(names.get(x.email)||x.email)}</strong><div class="meta">${esc(x.email)}</div><div class="meta">Grades: ${esc((x.grades||[]).join(', ')||'none')} · Individual students: ${x.students?.length||0}</div></div><button data-edit-dean="${esc(x.email)}">Edit</button></div>`).join(''):'<div class="empty">No Dean assignments configured.</div>';$('scopeList').querySelectorAll('[data-edit-dean]').forEach(b=>b.addEventListener('click',()=>selectDean(b.dataset.editDean)));}
  function selectDean(email){$('scopeDean').value=email;const r=scopeAssignments()[email]||{grades:[],students:[]};document.querySelectorAll('[data-grade]').forEach(c=>c.checked=(r.grades||[]).includes(c.dataset.grade));$('scopeStudents').value=(r.students||[]).join('\n')}
  async function openScope(){state.staff=(await api('/admin/view_as/staff')).staff||[];state.scopeConfig=(await api('/admin/dean/scope')).config||{deans:{}};$('scopeDean').innerHTML='<option value="">Choose staff…</option>'+state.staff.map(x=>`<option value="${esc(x.email)}">${esc(x.name||x.email)} — ${esc(x.email)}</option>`).join('');$('gradeChecks').innerHTML=['6','7','8','9','10','11','12'].map(g=>`<label><input type="checkbox" data-grade="${g}"> ${g}</label>`).join('');$('scopeStudents').value='';renderScopeList();$('scopeModal').hidden=false}
  async function saveScope(action='save'){const email=$('scopeDean').value;if(!email){$('scopeStatus').textContent='Choose a staff member.';return}const grades=[...document.querySelectorAll('[data-grade]:checked')].map(x=>x.dataset.grade),students=$('scopeStudents').value.split(/[,;\s]+/).filter(Boolean);if(action==='delete'&&!confirm(`Remove Dean Dashboard assignment for ${email}?`))return;const j=await api('/admin/dean/scope',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,email,grades,students})});state.scopeConfig=j.config||state.scopeConfig;$('scopeStatus').textContent=action==='delete'?'Assignment removed.':'Assignment saved.';if(action==='delete'){document.querySelectorAll('[data-grade]').forEach(c=>c.checked=false);$('scopeStudents').value=''}renderScopeList()}
  async function boot(){const access=await api('/admin/access');if(!access?.can?.dean_dashboard&&!access?.can?.super_admin)throw new Error('Dean Dashboard access required.');state.access=access;$('loginCard').hidden=true;$('app').hidden=false;await load();const u=new URL(location.href),osis=u.searchParams.get('osis');if(osis)await openStudent(osis)}
  async function googleLogin(resp){try{const r=await fetch(new URL('/admin/session/login_google',API_BASE),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({id_token:resp.credential}),credentials:'include'});const j=await r.json();if(j.sid)setSid(j.sid);if(!r.ok||!j.ok)throw new Error(j.error||`HTTP ${r.status}`);await boot()}catch(e){$('loginOut').textContent=`Login failed: ${e.message}`}}
  function bind(){$('preset').addEventListener('change',()=>{const c=$('preset').value==='custom';$('startWrap').hidden=!c;$('endWrap').hidden=!c});$('applyBtn').addEventListener('click',()=>load().catch(e=>status(e.message,'error')));$('refreshBtn').addEventListener('click',()=>load().catch(e=>status(e.message,'error')));$('gradeFilter').addEventListener('change',renderQueue);$('focusFilter').addEventListener('change',renderQueue);$('searchInput').addEventListener('input',renderQueue);$('closeStudentBtn').addEventListener('click',()=>{$('studentPanel').hidden=true;state.selected=null;state.detail=null});$('studentLookupBtn').addEventListener('click',()=>{if(state.selected)location.href=`./student_view.html?osis=${encodeURIComponent(state.selected)}`});$('newInterventionBtn').addEventListener('click',openIntervention);$('closeInterventionBtn').addEventListener('click',()=>{$('interventionModal').hidden=true});$('interventionModal').addEventListener('click',e=>{if(e.target===$('interventionModal'))$('interventionModal').hidden=true});$('intFollow').addEventListener('change',()=>{$('intDueWrap').hidden=!$('intFollow').checked});$('saveInterventionBtn').addEventListener('click',saveIntervention);$('manageScopeBtn').addEventListener('click',()=>openScope().catch(e=>status(e.message,'error')));$('closeScopeBtn').addEventListener('click',()=>{$('scopeModal').hidden=true});$('scopeModal').addEventListener('click',e=>{if(e.target===$('scopeModal'))$('scopeModal').hidden=true});$('scopeDean').addEventListener('change',()=>selectDean($('scopeDean').value));$('saveScopeBtn').addEventListener('click',()=>saveScope('save').catch(e=>$('scopeStatus').textContent=e.message));$('deleteScopeBtn').addEventListener('click',()=>saveScope('delete').catch(e=>$('scopeStatus').textContent=e.message))}
  async function init(){bind();try{await boot();return}catch{}try{const start=Date.now();while(!window.google?.accounts?.id){if(Date.now()-start>8000)throw new Error('Google sign-in failed to load');await new Promise(r=>setTimeout(r,50))}google.accounts.id.initialize({client_id:document.querySelector('meta[name="google-client-id"]')?.content||'',callback:googleLogin,ux_mode:'popup',use_fedcm_for_prompt:true});google.accounts.id.renderButton($('g_id_signin'),{theme:'outline',size:'large'});$('loginOut').textContent='Please sign in…'}catch(e){$('loginOut').textContent=e.message}}
  window.addEventListener('DOMContentLoaded',init);
})();
