'use strict';
const API_BASE=(document.querySelector('meta[name="api-base"]')?.content||'').replace(/\/*$/,'')+'/';
const CLIENT_ID=document.querySelector('meta[name="google-client-id"]')?.content||'';
const $=id=>document.getElementById(id);
let CURRENT=null,SECTION_ROWS=[],IS_ADMIN=false;
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')}
function sid(){return window.EAGLENEST_AUTH?.getSid?.()||''}
async function api(path,init={}){const h=new Headers(init.headers||{});if(sid())h.set('x-admin-session',sid());const r=await fetch(new URL(path,API_BASE),{...init,headers:h,credentials:'include',cache:'no-store'});const next=r.headers.get('x-admin-session');if(next)window.EAGLENEST_AUTH?.setSid?.(next);const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.error||`HTTP ${r.status}`);return j}
function nice(v){if(!v)return '—';const d=new Date(v);return Number.isFinite(d.getTime())?d.toLocaleString('en-US',{dateStyle:'medium',timeStyle:v.includes('T')?'short':undefined,timeZone:'America/New_York'}):v}
function percent(r){return r?.grading_completion==null?'—':Number(r.grading_completion).toFixed(1)+'%'}
function pill(status){const lookup={UPCOMING:['Upcoming','gbNeutral'],PENDING_GRADING:['Pending grading','gbWarn'],FULLY_GRADED:['Fully graded','gbGood'],NO_ACTIVE_ENROLLMENT:['No active enrollment','gbNeutral']};const [name,klass]=lookup[status]||[status,'gbNeutral'];return `<span class="gbPill ${klass}">${esc(name)}</span>`}
function setError(e){$('error').hidden=!e;$('error').textContent=String(e||'')}
function renderSummary(s){const cards=[['My / selected sections',s.section_count],['Assignments retrieved',s.assignment_count],['Due assignments graded',`${s.fully_graded_count}/${s.due_count}`],['Recorded score completion',s.grading_completion==null?'—':Number(s.grading_completion).toFixed(1)+'%'],['Due assignments pending',s.outstanding_count]];$('kpis').innerHTML=cards.map(([name,v])=>`<div class="gbKpi"><span>${esc(name)}</span><strong>${esc(v)}</strong></div>`).join('')}
function renderTable(){const q=$('search').value.trim().toLowerCase();const teacher=$('teacherFilter').value;const visible=SECTION_ROWS.filter(r=>(!teacher||r.teacher_email===teacher)&&(!q||[r.section_code,r.teacher_name,r.course_number].some(v=>String(v||'').toLowerCase().includes(q))));$('listCaption').textContent=`${visible.length} section(s) · click a course for its assignment breakdown.`;
  $('table').innerHTML=visible.length?`<table><thead><tr><th>Section</th>${IS_ADMIN?'<th>Teacher</th>':''}<th>Enrolled</th><th>Retrieved assignments</th><th>Due fully graded</th><th>Recorded completion</th><th>Pending due</th><th>Last score entry</th></tr></thead><tbody>${visible.map(r=>`<tr><td><button class="gbRowButton" data-section="${esc(r.section_dcid)}">${esc(r.section_code)}</button>${r.coverage==='NO_RETRIEVED_ASSIGNMENTS'?'<small>No returned scored assignments</small>':''}</td>${IS_ADMIN?`<td>${esc(r.teacher_name||'Unmapped teacher')}<small>${esc(r.teacher_email||'Email not mapped')}</small></td>`:''}<td>${r.enrolled_count}</td><td>${r.assignment_count}</td><td>${r.fully_graded_count}/${r.due_count}</td><td>${percent(r)}</td><td class="${r.outstanding_count?'gbWarn':'gbGood'}">${r.outstanding_count}</td><td>${esc(r.latest_score_entry||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="gbEmpty">No sections match your filters, or your teacher email has not yet been mapped to a PowerSchool section.</div>';
  $('table').querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>showSection(b.dataset.section));}
async function showSection(dcid){$('details').showModal();$('detailTitle').textContent='Loading section…';$('detailBody').innerHTML='';try{const data=await api('/admin/gradebook-analytics/section?section_dcid='+encodeURIComponent(dcid));$('detailTitle').textContent=data.section.section_code+' · '+(data.section.teacher_name||'');$('detailMeta').textContent=`${data.assignments.length} assignment(s) retrieved · ${data.section.enrolled_count} enrolled · completion ${percent(data.section)}`;
  $('detailBody').innerHTML=data.assignments.length?`<table><thead><tr><th>Due</th><th>Assignment</th><th>Category</th><th>Points</th><th>Recorded / expected</th><th>Status</th><th>Flags</th></tr></thead><tbody>${data.assignments.map(a=>`<tr><td>${esc(a.due_date)}</td><td>${esc(a.name)}${a.counted?'':'<small>Not counted in final grade</small>'}</td><td>${esc(a.category||'Uncategorized')}</td><td>${a.max_points??'—'}</td><td>${a.entered_scores}/${a.expected_scores}<small>${a.exempt_count} exempt</small></td><td>${pill(a.status)}</td><td><span class="${a.unentered_count?'gbBad':''}">${a.unentered_count} unentered</span><small>${a.missing_flag_count} missing · ${a.absent_flag_count} absent · ${a.incomplete_flag_count} incomplete</small>${a.nonstandard_max?'<small class="gbWarn">Review maximum-point rule</small>':''}${a.overmax_count?`<small class="gbWarn">${a.overmax_count} score(s) over maximum</small>`:''}</td></tr>`).join('')}</tbody></table>`:'<div class="gbEmpty">No assignment records were returned for this section. The existing PowerSchool query excludes assignments with no qualifying score records.</div>';
}catch(e){$('detailTitle').textContent='Unable to load section';$('detailBody').textContent=e.message||String(e)}}
async function renderHistory(){try{const d=await api('/admin/gradebook-analytics/history');$('history').textContent=d.history?.length?d.history.map(s=>`${s.snapshot_date} · published ${nice(s.published_at)}`).join('  ·  '):'No earlier snapshots yet.'}catch{$('history').textContent='History temporarily unavailable.'}}
async function load(){setError('');$('table').textContent='Loading weekly report…';try{const data=await api('/admin/gradebook-analytics/overview');$('login').hidden=true;$('app').hidden=false;CURRENT=data;IS_ADMIN=data.viewer?.role==='admin';$('listTitle').textContent=IS_ADMIN?'Schoolwide sections':'My Sections';if(!data.snapshot){$('table').innerHTML='<div class="gbEmpty">No published gradebook analytics snapshot yet. Run Cloud Run /run?mode=eaglenest after both source exports show SUCCESS.</div>';$('kpis').innerHTML='';return}
  $('meta').textContent=`Assignment data refreshed ${nice(data.snapshot.assignment_export_completed_at)} · roster refreshed ${nice(data.snapshot.dde_export_completed_at)} · report published ${nice(data.snapshot.published_at)} · school ${data.snapshot.school_id}, term ${data.snapshot.term_id}`;
  $('coverage').textContent=data.snapshot.coverage_note||'';
  SECTION_ROWS=data.sections||[];
  const teachers=[...new Map(SECTION_ROWS.filter(s=>s.teacher_email).map(s=>[s.teacher_email,s.teacher_name||s.teacher_email])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));
  $('teacherFilterWrap').hidden=!IS_ADMIN;$('teacherFilter').innerHTML='<option value="">All teachers</option>'+teachers.map(([email,name])=>`<option value="${esc(email)}">${esc(name)}</option>`).join('');renderSummary(data.summary||{});renderTable();renderHistory();
}catch(e){setError(e.message||String(e));$('table').textContent='Could not load report.'}}
async function signIn(){try{await api('/admin/access');await load()}catch{if(!window.google?.accounts?.id){$('loginMessage').textContent='Loading Google Sign-In…';let i=0;while(!window.google?.accounts?.id&&i++<100)await new Promise(r=>setTimeout(r,80));}if(!window.google?.accounts?.id){$('loginMessage').textContent='Google Sign-In failed to load';return}window.google.accounts.id.initialize({client_id:CLIENT_ID,callback:async r=>{try{const response=await fetch(new URL('/admin/session/login_google',API_BASE),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({id_token:r.credential}).toString(),credentials:'include'});const j=await response.json();if(!response.ok||!j.ok)throw new Error(j.error||'Sign-in failed');window.EAGLENEST_AUTH?.setSid?.(j.sid||response.headers.get('x-admin-session'));await load()}catch(e){$('loginMessage').textContent=e.message||String(e)}}});window.google.accounts.id.renderButton($('g_id_signin'),{theme:'outline',size:'large'});$('loginMessage').textContent='Please sign in with your school account.'}}
$('refresh').onclick=load;$('search').oninput=renderTable;$('teacherFilter').onchange=renderTable;$('closeDetails').onclick=()=>$('details').close();window.addEventListener('DOMContentLoaded',signIn);
