// EAGLENEST_GRADING_FINAL_V1
// EAGLENEST_GRADING_V1
(() => {
  'use strict';
  const API_BASE = (() => {
    const raw = String(document.querySelector('meta[name="api-base"]')?.content || location.origin).trim();
    try { return new URL(raw).toString().replace(/\/+$/, '/') } catch { return location.origin + '/' }
  })();
  const CLIENT_ID = String(document.querySelector('meta[name="google-client-id"]')?.content || '').trim();
  const $ = (id) => document.getElementById(id);
  const state = {
    access:null,status:null,terms:null,sections:[],assignments:[],categories:[],roster:[],
    sectionId:'',assignmentId:'',currentByEmail:new Map(),baselineByEmail:new Map(),preview:null,previewFingerprint:''
  };

  function sid(){ return window.EAGLENEST_AUTH?.getSid?.() || ''; }
  function setSid(v){ try{window.EAGLENEST_AUTH?.setSid?.(v)}catch{} }
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function txt(v){return String(v==null?'':v).trim()}
  function lower(v){return txt(v).toLowerCase()}
  function boolish(v){return v===true||v===1||String(v).toLowerCase()==='true'||String(v)==='1'}
  function numberOrBlank(v){const n=Number(v);return v===''||v==null||!Number.isFinite(n)?'':String(n)}
  function today(){const d=new Date();return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
  function showError(message=''){$('errorCard').hidden=!message;$('errorCard').textContent=message?String(message):''}
  function setSetup(message=''){$('setupCard').hidden=!message;$('setupMessage').textContent=message||''}

  async function api(path, init={}){
    const h=new Headers(init.headers||{});const s=sid();if(s&&!h.has('x-admin-session'))h.set('x-admin-session',s);
    const r=await fetch(new URL(path,API_BASE),{...init,headers:h,credentials:'include',cache:'no-store'});
    const next=r.headers.get('x-admin-session')||r.headers.get('X-Admin-Session');if(next)setSid(next);
    const j=await r.json().catch(()=>({}));
    if(!r.ok||j?.ok===false){const e=new Error(j?.message||j?.error||`HTTP ${r.status}`);e.status=r.status;e.body=j;throw e}return j;
  }

  function sectionLabel(s){const b=[];if(s.courseNumber)b.push(s.courseNumber);if(s.sectionNumber)b.push(`#${s.sectionNumber}`);if(s.teacherLastFirst)b.push(s.teacherLastFirst);if(s.room)b.push(`Room ${s.room}`);if(s.expression)b.push(s.expression);if(s.id)b.push(`ID ${s.id}`);return b.join(' · ')||`Section ${s.id||''}`}
  function assignmentName(a){return txt(a?.name||a?.assignmentTitle||a?.title)||'(untitled)'}
  function assignmentId(a){return txt(a?.assignmentsectionid||a?.assignmentSectionId||a?.ptp_assignmentsectionid)}
  function assignmentTermCode(a){return txt(a?.reporting_term?.code)}
  function assignmentLabel(a){const bits=[assignmentName(a)];if(a.maxPoints!=null)bits.push(`${a.maxPoints} pts`);if(a.dueDate)bits.push(`due ${a.dueDate}`);bits.push(assignmentTermCode(a)||'NO TERM');if(a.eaglenest_writable===false)bits.push('LOCKED');return bits.join(' · ')}
  function currentAssignment(){return state.assignments.find(a=>assignmentId(a)===String(state.assignmentId))||null}

  function renderStatus(){const s=state.status||{};$('systemMode').textContent=txt(s.system_mode||'unknown').toUpperCase();$('bridgeState').textContent=s.bridge_configured?(s.bridge_error?'Connected with warning':'Connected'):'Not configured';const cur=s.reporting_terms?.current_assignment_term;$('currentTerm').textContent=cur?`${cur.code} · ${cur.name}`:'Not configured / no match';
    if(!s.bridge_configured)setSetup(`The native grading page is installed, but the PowerTeacher grading service is not configured in the EagleNEST Worker. Missing: ${(s.bridge_missing||[]).join(', ')||'bridge URL/token'}.`);else if(s.bridge_error)setSetup(`PowerTeacher bridge check failed: ${s.bridge_error.message||s.bridge_error.error||'unknown error'}`);else if((s.reporting_terms?.configured_assignment_terms||0)===0)setSetup('Configure at least one assignment reporting term (Q1/Q2/etc.) before grading.');else setSetup('');
  }

  function renderTerms(){const config=state.terms?.config||{};const terms=(config.terms||[]).filter(t=>t.enabled&&t.assignment_term);const current=state.terms?.current_assignment_term?.code||state.status?.reporting_terms?.current_assignment_term?.code||'';$('termFilter').innerHTML='<option value="">All terms</option>'+terms.map(t=>`<option value="${esc(t.code)}">${esc(t.code)} · ${esc(t.name)}</option>`).join('');if(current&&terms.some(t=>t.code===current))$('termFilter').value=current;}

  function renderSections(){const options=state.sections.map(s=>`<option value="${esc(s.id)}">${esc(sectionLabel(s))}</option>`).join('');$('sectionSelect').innerHTML=options||'<option value="">No PowerTeacher sections returned</option>';if(state.sectionId&&state.sections.some(s=>String(s.id)===String(state.sectionId)))$('sectionSelect').value=state.sectionId;else state.sectionId=String($('sectionSelect').value||'');}

  function filteredAssignments(){const term=$('termFilter').value;return state.assignments.filter(a=>!term||assignmentTermCode(a)===term)}
  function renderAssignments(preferred=''){const rows=filteredAssignments();$('assignmentSelect').innerHTML=rows.length?rows.map(a=>`<option value="${esc(assignmentId(a))}">${esc(assignmentLabel(a))}</option>`).join(''):'<option value="">No assignments in this term</option>';const wanted=preferred||state.assignmentId;if(wanted&&rows.some(a=>assignmentId(a)===String(wanted)))$('assignmentSelect').value=String(wanted);state.assignmentId=String($('assignmentSelect').value||'');renderAssignmentCard();}
  function renderAssignmentCard(){const a=currentAssignment();$('assignmentCard').hidden=!a;$('gradingCard').hidden=!a;if(!a)return;$('assignmentTitle').textContent=assignmentName(a);const term=a.reporting_term;const meta=[a.dueDate?`Due ${a.dueDate}`:'No due date',a.maxPoints!=null?`${a.maxPoints} points`:'Points unknown',term?`${term.code} · ${term.name}`:'No EagleNEST assignment term'].join(' · ');$('assignmentMeta').textContent=meta;const badge=$('assignmentBadge');if(a.eaglenest_writable!==false){badge.textContent='Open for grading';badge.className='grading-pill open'}else if(a.eaglenest_writable_reason==='reporting_term_unresolved'){badge.textContent='No reporting term';badge.className='grading-pill warn'}else{badge.textContent=a.reporting_term?.lock_state?.reason==='auto'?'Auto-locked':'Locked';badge.className='grading-pill locked'} }

  function categoryLabel(c){const bits=[];if(c.name)bits.push(c.name);if(c.defaultScoreEntryPoints!=null)bits.push(`${c.defaultScoreEntryPoints} pts`);if(c.defaultWeight!=null)bits.push(`weight ${c.defaultWeight}`);if(c.isInFinalGrades===false)bits.push('not in final grades');return bits.join(' · ')||`Category ${c.teacherCategoryId||''}`}
  function renderCategories(){$('newCategory').innerHTML='<option value="">Default category (auto)</option>'+state.categories.map(c=>`<option value="${esc(c.teacherCategoryId)}">${esc(categoryLabel(c))}</option>`).join('')}

  function currentScoreValue(cur){if(!cur||typeof cur!=='object')return'';const v=cur.scorepoints??cur.actualscoreentered??cur.scorePoints??cur.score??cur.value;return numberOrBlank(v)}
  function currentStatus(cur){if(!cur||typeof cur!=='object')return'regular';if(boolish(cur.isexempt??cur.isExempt))return'exempt';if(boolish(cur.ismissing??cur.isMissing))return'missing';if(boolish(cur.isabsent??cur.isAbsent))return'absent';if(boolish(cur.isincomplete??cur.isIncomplete))return'incomplete';return'regular'}
  function currentLate(cur){return boolish(cur?.islate??cur?.isLate)}
  function rosterEmail(r){return lower(r?.email||r?.studentEmail)}
  function rosterStudentNumber(r){return txt(r?.studentNumber||r?.student_number||r?.osis)}
  function rowBaseline(email){return state.baselineByEmail.get(email)||{score:'',status:'regular',late:false,comment:''}}
  function rowValue(tr){const score=tr.querySelector('[data-score]')?.value?.trim()||'';const status=tr.querySelector('[data-status]')?.value||'regular';const late=!!tr.querySelector('[data-late]')?.checked;const comment=tr.querySelector('[data-comment]')?.value||'';return{score,status,late,comment}}
  function rowChanged(tr){const email=tr.dataset.email;const a=rowBaseline(email),b=rowValue(tr);const effectiveScore=(b.score===''&&b.status==='regular'&&a.status==='regular')?a.score:b.score;return String(a.score)!==String(effectiveScore)||a.status!==b.status||a.late!==b.late||a.comment!==b.comment}
  function invalidatePreview(){state.preview=null;state.previewFingerprint='';$('submitBtn').disabled=true;document.querySelectorAll('#scoreBody tr[data-email]').forEach(tr=>{tr.classList.toggle('dirty-row',rowChanged(tr));const cell=tr.querySelector('[data-preview-cell]');if(cell)cell.innerHTML=rowChanged(tr)?'<span class="muted">Needs preview</span>':'<span class="muted">—</span>'});updateScoreSummary()}
  function changedRows(){return [...document.querySelectorAll('#scoreBody tr[data-email]')].filter(tr=>!tr.classList.contains('disabled-row')&&rowChanged(tr))}
  function scorePayloadRows(){return changedRows().map(tr=>{const email=tr.dataset.email;const v=rowValue(tr);const numeric=v.score===''?null:Number(v.score);return{studentEmail:email,score:Number.isFinite(numeric)?numeric:null,comment:v.comment,isLate:v.late,isMissing:v.status==='missing',isExempt:v.status==='exempt',isAbsent:v.status==='absent',isIncomplete:v.status==='incomplete',status:v.status}}).filter(r=>r.status!=='regular'||r.score!==null||r.comment||r.isLate)}
  function requestBody(){const a=currentAssignment();return{psSectionId:state.sectionId,ptpAssignmentsectionid:state.assignmentId,maxPoints:a?.maxPoints,scores:scorePayloadRows()}}
  function fingerprint(){return JSON.stringify(requestBody())}

  function updateScoreSummary(){const total=state.roster.length;const withEmail=state.roster.filter(r=>rosterEmail(r)).length;const dirty=changedRows().length;$('scoreSummary').textContent=`${total} student(s) · ${withEmail} writable by email · ${dirty} row(s) changed${state.preview?' · preview loaded':''}.`;}
  function renderScores(){const a=currentAssignment();if(!a){$('scoreBody').innerHTML='<tr><td colspan="7" class="muted">Choose an assignment.</td></tr>';return}state.baselineByEmail.clear();const html=state.roster.map(r=>{const email=rosterEmail(r);const cur=state.currentByEmail.get(email)||null;const score=currentScoreValue(cur);const status=currentStatus(cur);const late=currentLate(cur);if(email)state.baselineByEmail.set(email,{score,status,late,comment:''});const disabled=!email||a.eaglenest_writable===false;return`<tr data-email="${esc(email)}" class="${disabled?'disabled-row':''}"><td><div class="student-main">${esc(r.lastfirst||r.name||'Student')}</div><div class="student-sub">${esc(rosterStudentNumber(r))}${email?` · ${esc(email)}`:' · No email — read/write unavailable'}</div></td><td>${esc(score||'blank')}</td><td><input class="score-input" data-score type="number" step="any" value="${esc(score)}" ${disabled?'disabled':''}></td><td><select class="status-select" data-status ${disabled?'disabled':''}>${['regular','missing','exempt','absent','incomplete'].map(x=>`<option value="${x}" ${x===status?'selected':''}>${x[0].toUpperCase()+x.slice(1)}</option>`).join('')}</select></td><td><input data-late type="checkbox" ${late?'checked':''} ${disabled?'disabled':''}></td><td><input class="comment-input" data-comment maxlength="2000" placeholder="Optional" ${disabled?'disabled':''}></td><td class="preview-cell" data-preview-cell><span class="muted">—</span></td></tr>`}).join('');$('scoreBody').innerHTML=html||'<tr><td colspan="7" class="muted">No roster rows returned.</td></tr>';document.querySelectorAll('#scoreBody input,#scoreBody select').forEach(el=>el.addEventListener('input',invalidatePreview));document.querySelectorAll('#scoreBody select,#scoreBody input[type="checkbox"]').forEach(el=>el.addEventListener('change',invalidatePreview));updateScoreSummary();}

  async function loadStatus(){state.status=await api('/admin/grading/status');renderStatus()}
  async function loadTerms(){state.terms=await api('/admin/reporting_terms');renderTerms()}
  // EAGLENEST_GRADING_SECTION_SCOPE_V1
  async function loadSections(){const showAll=state.access?.view_as?.active!==true&&(state.access?.can?.admin===true||state.access?.can?.super_admin===true);const j=await api('/admin/grading/sections'+(showAll?'?all=true':''));state.sections=(j.sections||[]).filter(s=>String(s.gradebooktype)==='2');renderSections();if(state.sectionId)await loadSectionData()}
  async function loadSectionData(){showError('');state.assignmentId='';state.preview=null;state.currentByEmail.clear();$('scoreBody').innerHTML='<tr><td colspan="7" class="muted">Loading section…</td></tr>';const id=state.sectionId;if(!id){state.assignments=[];state.categories=[];state.roster=[];renderAssignments();return}const [a,c,r]=await Promise.all([api(`/admin/grading/assignments?sectionId=${encodeURIComponent(id)}`),api(`/admin/grading/categories?sectionId=${encodeURIComponent(id)}`),api(`/admin/grading/roster?sectionId=${encodeURIComponent(id)}`)]);state.assignments=a.assignments||[];state.categories=c.categories||[];state.roster=r.roster||[];renderCategories();renderAssignments();if(state.assignmentId)await loadCurrentScores()}
  async function loadCurrentScores(){const a=currentAssignment();if(!a){renderScores();return}showError('');$('scoreBody').innerHTML='<tr><td colspan="7" class="muted">Loading current PowerTeacher scores…</td></tr>';const students=state.roster.map(r=>({studentEmail:rosterEmail(r)})).filter(x=>x.studentEmail);const j=await api('/admin/grading/scores/current',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({psSectionId:state.sectionId,ptpAssignmentsectionid:state.assignmentId,maxPoints:a.maxPoints,students})});state.currentByEmail=new Map((j.rows||[]).map(r=>[lower(r.studentEmail),r.currentScore||null]));state.preview=null;state.previewFingerprint='';$('submitBtn').disabled=true;renderScores()}

  async function previewChanges(){const rows=scorePayloadRows();if(!rows.length)throw new Error('Make at least one score/status change first.');const body=requestBody();const j=await api('/admin/grading/scores/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});state.preview=j;state.previewFingerprint=fingerprint();const byEmail=new Map((j.rows||[]).map(r=>[lower(r.studentEmail),r]));let ready=0,errors=0,changes=0;document.querySelectorAll('#scoreBody tr[data-email]').forEach(tr=>{const cell=tr.querySelector('[data-preview-cell]');if(!cell)return;const p=byEmail.get(tr.dataset.email);if(!p){cell.innerHTML=rowChanged(tr)?'<span class="preview-error">Not returned</span>':'<span class="muted">—</span>';return}const action=p.status!=='READY'?'ERROR':(p.changeAction||'READY');if(p.status==='READY')ready++;else errors++;if(['ADD','UPDATE'].includes(action))changes++;const cls=action==='ADD'?'preview-add':action==='UPDATE'?'preview-update':action==='NO_CHANGE'?'preview-nochange':'preview-error';cell.innerHTML=`<strong class="${cls}">${esc(action)}</strong>${p.message?`<div>${esc(p.message)}</div>`:''}`});$('submitBtn').disabled=errors>0||ready===0||currentAssignment()?.eaglenest_writable===false;$('scoreSummary').textContent=`Preview: ${ready} ready · ${changes} add/update · ${errors} error(s). Review before submitting.`}
  async function submitChanges(){if(!state.preview||state.previewFingerprint!==fingerprint())throw new Error('Your scores changed after the last preview. Preview again first.');if($('submitBtn').disabled)throw new Error('This preview cannot be submitted.');const rows=scorePayloadRows();if(!rows.length)throw new Error('No changes to submit.');const a=currentAssignment();if(!confirm(`Submit ${rows.length} changed row(s) for “${assignmentName(a)}” to PowerTeacher Pro?`))return;$('submitBtn').disabled=true;const j=await api('/admin/grading/scores/push',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(requestBody())});await loadCurrentScores();$('scoreSummary').textContent=`Submitted ${j.submitted_count||rows.length} row(s) to PowerTeacher. Current scores reloaded.`}

  async function previewNewTerm(){const date=$('newDueDate').value;const box=$('newTermPreview');$('createAssignmentBtn').disabled=true;if(!date){box.className='term-preview muted';box.textContent='Choose a due date.';return}try{const j=await api(`/admin/reporting_terms/resolve?date=${encodeURIComponent(date)}`);const r=j.resolution;if(r?.status==='matched'&&r.term){if(r.term.effective_locked){box.className='term-preview bad';box.textContent=`${r.term.code} · ${r.term.name} is locked. Choose an open-term due date.`}else{box.className='term-preview good';box.textContent=`Counts toward ${r.term.code} · ${r.term.name} (${r.term.start_date} – ${r.term.end_date}).`;$('createAssignmentBtn').disabled=state.status?.writes_allowed!==true}}else{box.className='term-preview warn';box.textContent='This date is not covered by an enabled assignment reporting term.'}}catch(e){box.className='term-preview bad';box.textContent=e.message}}
  function openNewAssignment(){if(!state.sectionId){showError('Choose a section first.');return}$('newTitle').value='';$('newPoints').value='100';$('newDueDate').value=today();$('newCountFinal').checked=true;$('newAssignmentError').hidden=true;renderCategories();$('newAssignmentDialog').showModal();previewNewTerm()}
  async function createAssignment(){const title=txt($('newTitle').value),maxPoints=Number($('newPoints').value),dueDate=$('newDueDate').value;if(!title)throw new Error('Assignment title is required.');if(!Number.isFinite(maxPoints)||maxPoints<0)throw new Error('Points must be 0 or greater.');const body={psSectionId:state.sectionId,assignmentTitle:title,maxPoints,dueDate,teacherCategoryId:$('newCategory').value||undefined,countInFinalGrade:$('newCountFinal').checked};const j=await api('/admin/grading/assignment/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const asid=txt(j.assignmentsection?.assignmentsectionid||j.assignmentsectionid||j.created?.assignmentsectionid);$('newAssignmentDialog').close();await loadSectionData();if(asid){$('termFilter').value='';renderAssignments(asid);state.assignmentId=String($('assignmentSelect').value||'');if(state.assignmentId)await loadCurrentScores()}}

  async function boot(){showError('');const access=await api('/admin/access');state.access=access;if(access?.can?.grading!==true)throw new Error('Your EagleNEST account does not currently have Grading access.');$('loginCard').hidden=true;$('app').hidden=false;$('viewerMeta').textContent=`${access.email||''}${access.role?` · ${access.role}`:''}${access.view_as?.active?' · read-only preview':''}`;await Promise.all([loadStatus(),loadTerms()]);if(state.status?.bridge_configured)await loadSections();else{$('sectionSelect').innerHTML='<option value="">Bridge setup required</option>'}}
  async function googleLogin(resp){try{const r=await fetch(new URL('/admin/session/login_google',API_BASE),{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({id_token:resp.credential}),credentials:'include'});const j=await r.json().catch(()=>({}));if(j.sid)setSid(j.sid);if(!r.ok||!j.ok)throw new Error(j.error||`HTTP ${r.status}`);await boot()}catch(e){$('loginOut').textContent=`Login failed: ${e.message}`}}
  async function initLogin(){try{await boot();return}catch{}try{const start=Date.now();while(!window.google?.accounts?.id){if(Date.now()-start>8000)throw new Error('Google sign-in failed to load');await new Promise(r=>setTimeout(r,60))}google.accounts.id.initialize({client_id:CLIENT_ID,callback:googleLogin,ux_mode:'popup',use_fedcm_for_prompt:true});google.accounts.id.renderButton($('g_id_signin'),{theme:'outline',size:'large'});$('loginOut').textContent='Please sign in…'}catch(e){$('loginOut').textContent=e.message}}

  $('sectionSelect').addEventListener('change',()=>{state.sectionId=String($('sectionSelect').value||'');loadSectionData().catch(e=>showError(e.message))});
  $('termFilter').addEventListener('change',()=>{state.assignmentId='';renderAssignments();if(state.assignmentId)loadCurrentScores().catch(e=>showError(e.message))});
  $('assignmentSelect').addEventListener('change',()=>{state.assignmentId=String($('assignmentSelect').value||'');renderAssignmentCard();loadCurrentScores().catch(e=>showError(e.message))});
  $('reloadAssignmentBtn').addEventListener('click',()=>loadCurrentScores().catch(e=>showError(e.message)));
  $('previewBtn').addEventListener('click',()=>previewChanges().catch(e=>showError(e.message)));
  $('submitBtn').addEventListener('click',()=>submitChanges().catch(e=>showError(e.message)));
  $('newAssignmentBtn').addEventListener('click',openNewAssignment);
  $('newDueDate').addEventListener('change',previewNewTerm);
  $('createAssignmentBtn').addEventListener('click',()=>createAssignment().catch(e=>{$('newAssignmentError').hidden=false;$('newAssignmentError').textContent=e.message}));
  $('refreshAllBtn').addEventListener('click',()=>boot().catch(e=>showError(e.message)));
  window.addEventListener('DOMContentLoaded',initLogin);
})();
