(() => {
  'use strict';
  const API_BASE=(()=>{const m=document.querySelector('meta[name="api-base"]');const raw=(m?.content||location.origin).trim();try{return new URL(raw).toString().replace(/\/+$/,'/')||location.origin+'/';}catch{return location.origin+'/';}})();
  const KEYS=['my_rosters_admin_session_v1','ss_admin_session_sid_v1','teacher_att_admin_session_v1','admin_session_v1','admin_session_sid'];
  const $=id=>document.getElementById(id);
  const state={custom:[],system:[],legacy:[],builder:new Map(),selected:new Map(),searchTimer:null};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  function sid(){try{for(const k of KEYS){const v=String(sessionStorage.getItem(k)||localStorage.getItem(k)||'').trim();if(v)return v;}}catch{}return '';}
  function stash(resp){try{const v=String(resp.headers.get('x-admin-session')||'').trim();if(v)for(const k of KEYS){try{sessionStorage.setItem(k,v);localStorage.setItem(k,v);}catch{}}}catch{}}
  async function api(path,init={}){const headers=new Headers(init.headers||{}),s=sid();if(s)headers.set('x-admin-session',s);const r=await fetch(new URL(path,API_BASE),{...init,headers,credentials:'include',cache:'no-store'});stash(r);const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok){const e=new Error(j?.detail||j?.error||`HTTP ${r.status}`);e.status=r.status;e.data=j;throw e;}return j;}
  async function copy(text,label){const value=String(text||'');if(!value){setBuilderStatus(`No ${label||'values'} to copy.`,false);return;}try{await navigator.clipboard.writeText(value);}catch{const ta=document.createElement('textarea');ta.value=value;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();}setBuilderStatus(`Copied ${label||'values'} to clipboard.`,true);}
  function setBuilderStatus(msg,ok=true){const el=$('builderStatus');el.className=`status ${ok?'ok':'bad'}`;el.textContent=String(msg||'');}
  function studentRowHtml(s,remove=false){return `<tr><td>${esc(s.name||'')}</td><td class="tiny">${esc(s.email||'')}</td><td class="mono">${esc(s.osis||'')}</td><td>${esc(s.grade||'')}</td>${remove?`<td><button type="button" data-remove-osis="${esc(s.osis)}">Remove</button></td>`:''}</tr>`;}
  function renderBuilder(){const rows=[...state.builder.values()].sort((a,b)=>String(a.name).localeCompare(String(b.name),undefined,{sensitivity:'base'}));$('builderCount').textContent=String(rows.length);$('builderBody').innerHTML=rows.length?rows.map(s=>studentRowHtml(s,true)).join(''):'<tr><td colspan="5" class="empty">No students selected yet.</td></tr>';}
  function clearBuilder(){state.builder.clear();$('rosterId').value='';$('rosterName').value='';$('pasteOsis').value='';$('pasteResult').textContent='';$('builderTitle').textContent='Create custom roster';renderBuilder();setBuilderStatus('Build a roster by searching students or pasting OSIS numbers.',true);}
  function addStudents(rows){let added=0;for(const s of Array.isArray(rows)?rows:[]){const osis=String(s?.osis||'').trim();if(!osis)continue;if(!state.builder.has(osis))added++;state.builder.set(osis,{osis,name:String(s.name||''),email:String(s.email||''),grade:String(s.grade||'')});}renderBuilder();return added;}
  async function addPasted(){const text=$('pasteOsis').value;if(!text.trim())return;try{const data=await api('/admin/my_rosters/resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text})});const added=addStudents(data.students);$('pasteResult').textContent=`${data.students.length} found · ${added} added${data.missing_osis?.length?` · ${data.missing_osis.length} not found: ${data.missing_osis.join(', ')}`:''}`;if(data.missing_osis?.length)setBuilderStatus(`Some pasted OSIS numbers were not found in the current active roster: ${data.missing_osis.join(', ')}`,false);else setBuilderStatus(`Added ${added} student(s) from pasted OSIS.`,true);}catch(e){setBuilderStatus(e.message,false);}}
  async function search(){const q=$('studentSearch').value.trim();const box=$('searchResults');if(q.length<2){box.innerHTML='';return;}try{const data=await api(`/admin/roster/search?q=${encodeURIComponent(q)}`,{method:'GET'});box.innerHTML=(data.results||[]).map(s=>`<div class="searchHit"><div><b>${esc(s.name||'')}</b><div class="tiny muted">${esc(s.email||'')} · ${esc(s.osis||'')} · Grade ${esc(s.grade||'')}</div></div><button type="button" data-add-search="${esc(s.osis)}" data-name="${esc(s.name||'')}" data-email="${esc(s.email||'')}" data-grade="${esc(s.grade||'')}">${state.builder.has(String(s.osis))?'Added':'Add'}</button></div>`).join('')||'<div class="muted tiny">No matches.</div>';}catch(e){box.innerHTML=`<div class="muted tiny">${esc(e.message)}</div>`;}}
  function allCatalog(){return [...state.custom,...state.system,...state.legacy];}
  function itemKey(row){return `${row.kind}|${row.id}`;}
  function rosterCard(row,editable=false,legacy=false){const key=itemKey(row),checked=state.selected.has(key);return `<div class="rosterCard" data-card-key="${esc(key)}"><div class="rosterTop"><input type="checkbox" data-select-roster="${esc(key)}" ${checked?'checked':''} aria-label="Select roster"><div class="rosterMain"><div class="rosterName">${esc(row.name||'Roster')}</div><div class="rosterMeta">${esc(row.kind==='system'?(row.system_type==='advisory'?'Current advisory roster':'Current class roster'):(legacy?`Previous ${row.source_label||''} roster`:'Saved roster'))} · ${Number(row.student_count||0)} student(s)${row.subtitle?` · ${esc(row.subtitle)}`:''}</div><div class="rosterActions"><button type="button" data-view-roster="${esc(key)}">View students</button>${editable?`<button type="button" data-edit-roster="${esc(key)}">Edit</button><button class="danger" type="button" data-delete-roster="${esc(key)}">Delete</button>`:''}${legacy?`<button class="primary" type="button" data-import-roster="${esc(key)}">Import to My Rosters</button>`:''}</div></div></div><div class="rosterDetails" data-details-for="${esc(key)}"><div class="muted tiny">Load students to view details.</div></div></div>`;}
  function renderCatalogs(){$('customCount').textContent=String(state.custom.length);$('customRosters').innerHTML=state.custom.length?state.custom.map(r=>rosterCard(r,true,false)).join(''):'<div class="empty">No custom rosters yet. Build one on the right.</div>';$('systemRosters').innerHTML=state.system.length?state.system.map(r=>rosterCard(r,false,false)).join(''):'<div class="empty">No current class/advisory rosters are mapped to this account.</div>';$('legacyCard').hidden=!state.legacy.length;$('legacyRosters').innerHTML=state.legacy.map(r=>rosterCard(r,false,true)).join('');updateSelectedToolbar();}
  async function refresh(){const data=await api('/admin/my_rosters',{method:'GET'});state.custom=Array.isArray(data.custom_rosters)?data.custom_rosters:[];state.system=Array.isArray(data.system_rosters)?data.system_rosters:[];state.legacy=Array.isArray(data.legacy_rosters)?data.legacy_rosters:[];const valid=new Set(allCatalog().map(itemKey));for(const key of [...state.selected.keys()])if(!valid.has(key))state.selected.delete(key);renderCatalogs();}
  function parseKey(key){const i=String(key||'').indexOf('|');return i<0?{kind:'',id:''}:{kind:key.slice(0,i),id:key.slice(i+1)};}
  async function detailForKey(key){const {kind,id}=parseKey(key);return api(`/admin/my_rosters/detail?kind=${encodeURIComponent(kind)}&id=${encodeURIComponent(id)}`,{method:'GET'});}
  async function viewRoster(key){const card=document.querySelector(`[data-card-key="${CSS.escape(key)}"]`);if(!card)return;const details=card.querySelector('.rosterDetails');if(card.classList.contains('open')){card.classList.remove('open');return;}card.classList.add('open');details.innerHTML='<div class="muted tiny">Loading students…</div>';try{const data=await detailForKey(key);const rows=data.students||[];details.innerHTML=`<div class="row tiny muted" style="margin-bottom:6px"><span>${rows.length} current students</span>${data.missing_osis?.length?`<span>· ${data.missing_osis.length} no longer in current roster</span>`:''}</div><div class="scroll"><table><thead><tr><th>Name</th><th>Email</th><th>OSIS</th><th>Grade</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${esc(s.name||'')}</td><td class="tiny">${esc(s.email||'')}</td><td class="mono">${esc(s.osis||'')}</td><td>${esc(s.grade||'')}</td></tr>`).join('')}</tbody></table></div>`;}catch(e){details.textContent=e.message;}}
  async function editRoster(key){try{const data=await detailForKey(key);state.builder.clear();addStudents(data.students||[]);$('rosterId').value=String(data.roster?.id||'');$('rosterName').value=String(data.roster?.name||'');$('builderTitle').textContent=`Edit roster — ${data.roster?.name||''}`;setBuilderStatus(data.missing_osis?.length?`Loaded current students. ${data.missing_osis.length} saved OSIS no longer appear in the active roster and will be removed if you save.`:'Loaded roster for editing.',true);window.scrollTo({top:0,behavior:'smooth'});}catch(e){setBuilderStatus(e.message,false);}}
  async function deleteRoster(key){const row=allCatalog().find(r=>itemKey(r)===key);if(!row||row.kind!=='custom')return;if(!confirm(`Delete saved roster “${row.name}”?`))return;try{await api('/admin/my_rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'delete',id:row.id})});if($('rosterId').value===row.id)clearBuilder();state.selected.delete(key);await refresh();setBuilderStatus(`Deleted “${row.name}”.`,true);}catch(e){setBuilderStatus(e.message,false);}}
  async function importLegacy(key){const row=allCatalog().find(r=>itemKey(r)===key);if(!row||row.kind!=='legacy')return;try{const data=await api('/admin/my_rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'import_legacy',id:row.id})});await refresh();setBuilderStatus(`Imported “${data.roster?.name||row.name}” into My Rosters.`,true);}catch(e){setBuilderStatus(e.message,false);}}
  async function saveBuilder(){const name=$('rosterName').value.trim(),students=[...state.builder.keys()];if(!name){setBuilderStatus('Name the roster before saving.',false);return;}if(!students.length){setBuilderStatus('Add at least one student before saving.',false);return;}try{const data=await api('/admin/my_rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'save',id:$('rosterId').value||undefined,name,osis_list:students})});$('rosterId').value=String(data.roster?.id||'');$('builderTitle').textContent=`Edit roster — ${data.roster?.name||name}`;await refresh();setBuilderStatus(`${data.updated?'Updated':'Saved'} “${data.roster?.name||name}” with ${data.roster?.student_count||students.length} student(s).`,true);}catch(e){if(e.data?.missing_osis?.length)setBuilderStatus(`Cannot save because these OSIS numbers are no longer active: ${e.data.missing_osis.join(', ')}`,false);else setBuilderStatus(e.message,false);}}
  async function aggregateSelected(){const items=[...state.selected.keys()].map(parseKey);if(!items.length)return null;return api('/admin/my_rosters/aggregate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({items})});}
  async function updateSelectedToolbar(){const n=state.selected.size;$('selectedRosterCount').textContent=String(n);for(const id of ['copySelectedEmails','copySelectedOsisColumn','copySelectedOsisComma','clearRosterSelection'])$(id).disabled=!n;if(!n){$('selectedStudentCount').textContent='0';return;}$('selectedStudentCount').textContent='…';try{const data=await aggregateSelected();if(state.selected.size===n)$('selectedStudentCount').textContent=String(data?.unique_student_count||0);}catch{$('selectedStudentCount').textContent='?';}}
  async function copySelected(kind){try{const data=await aggregateSelected();if(!data)return;const text=kind==='emails'?(data.emails||[]).join(', '):kind==='column'?(data.osis_list||[]).join('\n'):(data.osis_list||[]).join(', ');await copy(text,kind==='emails'?`${data.emails?.length||0} email addresses`:`${data.osis_list?.length||0} OSIS numbers`);}catch(e){setBuilderStatus(e.message,false);}}
  function copyBuilder(kind){const rows=[...state.builder.values()].sort((a,b)=>String(a.name).localeCompare(String(b.name)));const text=kind==='emails'?rows.map(x=>x.email).filter(Boolean).join(', '):kind==='column'?rows.map(x=>x.osis).join('\n'):rows.map(x=>x.osis).join(', ');copy(text,kind==='emails'?`${rows.filter(x=>x.email).length} email addresses`:`${rows.length} OSIS numbers`);}
  function wire(){
    $('addPastedBtn').addEventListener('click',addPasted);$('studentSearch').addEventListener('input',()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(search,180);});
    $('searchResults').addEventListener('click',e=>{const b=e.target.closest('[data-add-search]');if(!b)return;addStudents([{osis:b.dataset.addSearch,name:b.dataset.name,email:b.dataset.email,grade:b.dataset.grade}]);search();});
    $('builderBody').addEventListener('click',e=>{const b=e.target.closest('[data-remove-osis]');if(!b)return;state.builder.delete(String(b.dataset.removeOsis));renderBuilder();});
    $('saveRosterBtn').addEventListener('click',saveBuilder);$('clearBuilderBtn').addEventListener('click',clearBuilder);
    $('copyBuilderEmails').addEventListener('click',()=>copyBuilder('emails'));$('copyBuilderOsisColumn').addEventListener('click',()=>copyBuilder('column'));$('copyBuilderOsisComma').addEventListener('click',()=>copyBuilder('comma'));
    document.addEventListener('click',e=>{const v=e.target.closest('[data-view-roster]');if(v)return void viewRoster(v.dataset.viewRoster);const ed=e.target.closest('[data-edit-roster]');if(ed)return void editRoster(ed.dataset.editRoster);const d=e.target.closest('[data-delete-roster]');if(d)return void deleteRoster(d.dataset.deleteRoster);const imp=e.target.closest('[data-import-roster]');if(imp)return void importLegacy(imp.dataset.importRoster);});
    document.addEventListener('change',e=>{const cb=e.target.closest('[data-select-roster]');if(!cb)return;const key=cb.dataset.selectRoster;if(cb.checked)state.selected.set(key,true);else state.selected.delete(key);updateSelectedToolbar();});
    $('copySelectedEmails').addEventListener('click',()=>copySelected('emails'));$('copySelectedOsisColumn').addEventListener('click',()=>copySelected('column'));$('copySelectedOsisComma').addEventListener('click',()=>copySelected('comma'));$('clearRosterSelection').addEventListener('click',()=>{state.selected.clear();renderCatalogs();});
  }
  async function init(){wire();renderBuilder();try{const access=await api('/admin/access',{method:'GET'});if(access?.can?.my_rosters!==true)throw new Error('My Rosters access is not enabled for this account.');$('app').hidden=false;await refresh();}catch(e){$('authCard').hidden=false;$('authCard').textContent=e.message||'Staff sign-in required.';}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
