(() => {
  'use strict';
  // EAGLENEST_MY_ROSTERS_COLLAB_V2
  const API_BASE=(()=>{const m=document.querySelector('meta[name="api-base"]');const raw=(m?.content||location.origin).trim();try{return new URL(raw).toString().replace(/\/+$/,'/')||location.origin+'/';}catch{return location.origin+'/';}})();
  const KEYS=['my_rosters_admin_session_v1','ss_admin_session_sid_v1','teacher_att_admin_session_v1','admin_session_v1','admin_session_sid'];
  const $=id=>document.getElementById(id);
  const state={owned:[],shared:[],hidden:[],system:[],legacy:[],staff:[],locations:[],builder:new Map(),selected:new Map(),searchTimer:null,builderMode:'create',builderBase:null}; // EAGLENEST_MY_ROSTER_SPECIAL_ACTIONS_V1
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  function sid(){try{for(const k of KEYS){const v=String(sessionStorage.getItem(k)||localStorage.getItem(k)||'').trim();if(v)return v;}}catch{}return '';}
  function stash(resp){try{const v=String(resp.headers.get('x-admin-session')||'').trim();if(v)for(const k of KEYS){try{sessionStorage.setItem(k,v);localStorage.setItem(k,v);}catch{}}}catch{}}
  async function api(path,init={}){const headers=new Headers(init.headers||{}),s=sid();if(s)headers.set('x-admin-session',s);const r=await fetch(new URL(path,API_BASE),{...init,headers,credentials:'include',cache:'no-store'});stash(r);const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok){const e=new Error(j?.detail||j?.message||j?.error||`HTTP ${r.status}`);e.status=r.status;e.data=j;throw e;}return j;}
  async function copy(text,label){const value=String(text||'');if(!value){setStatus(`No ${label||'values'} to copy.`,false);return;}try{await navigator.clipboard.writeText(value);}catch{const ta=document.createElement('textarea');ta.value=value;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();}setStatus(`Copied ${label||'values'} to clipboard.`,true);}
  function setStatus(msg,ok=true){const el=$('builderStatus');if(!el)return;el.className=`status ${ok?'ok':'bad'}`;el.textContent=String(msg||'');}
  function keyOf(r){return `${r.kind||'custom'}|${r.id}`;}
  function parseKey(key){const i=String(key||'').indexOf('|');return i<0?{kind:'',id:''}:{kind:key.slice(0,i),id:key.slice(i+1)};}
  function allCatalog(){return [...state.owned,...state.shared,...state.hidden,...state.system,...state.legacy];}
  function findRow(key){return allCatalog().find(r=>keyOf(r)===key)||null;}
  function permissionLabel(p){return ({owner:'Owner',admin:'Roster Admin',edit:'Editor',suggest:'Suggester',view:'Viewer'})[p]||'View';}
  function studentRowHtml(s,remove=false){return `<tr><td>${esc(s.name||'')}</td><td class="tiny">${esc(s.email||'')}</td><td class="mono">${esc(s.osis||'')}</td><td>${esc(s.grade||'')}</td>${remove?`<td><button type="button" data-remove-osis="${esc(s.osis)}">Remove</button></td>`:''}</tr>`;}
  function specialActionLabel(row){return row?.special_action_type==='sports_team'?'Sports Team':row?.special_action_type==='club'?'Club':'';}
  function specialActionMeta(row){const label=specialActionLabel(row);if(!label)return'';return `${label} · ${row?.special_action_home_room?`Home: ${row.special_action_home_room}`:'No default location'}`;}
  function renderSpecialActionUi(){
    const type=$('specialActionType')?.value||'',room=$('specialActionHomeRoom')?.value.trim()||'',suggest=state.builderMode==='suggest';
    if($('specialActionType'))$('specialActionType').disabled=suggest;
    if($('specialActionHomeRoom'))$('specialActionHomeRoom').disabled=suggest||!type;
    if($('specialActionHint'))$('specialActionHint').textContent=suggest
      ? 'Special Actions cannot be changed through a suggestion. An Editor or Roster Admin can change them directly.'
      : type?`${type==='sports_team'?'Sports Team':'Club'} will be published to the After-School activity picker${room?` with ${room} as the default location`:' with no required location'}.`:'No Special Action. This roster will not appear as an After-School activity.';
  }
  function renderSpecialActionLocations(){const list=$('specialActionLocations');if(!list)return;list.innerHTML=(state.locations||[]).map(x=>`<option value="${esc(x)}"></option>`).join('');}
  function renderBuilder(){const rows=[...state.builder.values()].sort((a,b)=>String(a.name).localeCompare(String(b.name),undefined,{sensitivity:'base'}));$('builderCount').textContent=String(rows.length);$('builderBody').innerHTML=rows.length?rows.map(s=>studentRowHtml(s,true)).join(''):'<tr><td colspan="5" class="empty">No students selected yet.</td></tr>';}
  function resetBuilderUi(){state.builderMode='create';state.builderBase=null;$('rosterId').value='';$('rosterVersion').value='';$('rosterName').value='';$('specialActionType').value='';$('specialActionHomeRoom').value='';$('pasteOsis').value='';$('pasteResult').textContent='';$('builderTitle').textContent='Create custom roster';$('saveRosterBtn').textContent='Save roster';$('suggestionNoteWrap').hidden=true;$('suggestionNote').value='';renderSpecialActionUi();}
  function clearBuilder(){state.builder.clear();resetBuilderUi();renderBuilder();setStatus('Build a roster by searching students or pasting OSIS numbers.',true);}
  function addStudents(rows){let added=0;for(const s of Array.isArray(rows)?rows:[]){const osis=String(s?.osis||'').trim();if(!osis)continue;if(!state.builder.has(osis))added++;state.builder.set(osis,{osis,name:String(s.name||''),email:String(s.email||''),grade:String(s.grade||'')});}renderBuilder();return added;}
  async function addPasted(){const text=$('pasteOsis').value;if(!text.trim())return;try{const data=await api('/admin/my_rosters/resolve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text})});const added=addStudents(data.students);$('pasteResult').textContent=`${data.students.length} found · ${added} added${data.missing_osis?.length?` · ${data.missing_osis.length} not found: ${data.missing_osis.join(', ')}`:''}`;setStatus(data.missing_osis?.length?`Some pasted OSIS numbers were not found: ${data.missing_osis.join(', ')}`:`Added ${added} student(s) from pasted OSIS.`,!data.missing_osis?.length);}catch(e){setStatus(e.message,false);}}
  async function search(){const q=$('studentSearch').value.trim(),box=$('searchResults');if(q.length<2){box.innerHTML='';return;}try{const data=await api(`/admin/my_rosters/student_search?q=${encodeURIComponent(q)}`,{method:'GET'});box.innerHTML=(data.results||[]).map(s=>`<div class="searchHit"><div><b>${esc(s.name||'')}</b><div class="tiny muted">${esc(s.email||'')} · ${esc(s.osis||'')} · Grade ${esc(s.grade||'')}</div></div><button type="button" data-add-search="${esc(s.osis)}" data-name="${esc(s.name||'')}" data-email="${esc(s.email||'')}" data-grade="${esc(s.grade||'')}">${state.builder.has(String(s.osis))?'Added':'Add'}</button></div>`).join('')||'<div class="muted tiny">No matches.</div>';}catch(e){box.innerHTML=`<div class="muted tiny">${esc(e.message)}</div>`;}}
  function metaText(row,section){if(section==='system')return row.system_type==='advisory'?'Current advisory roster':'Current class roster';if(section==='legacy')return `Previous ${row.source_label||''} roster`;const special=specialActionMeta(row),base=(section==='shared'||section==='hidden')?`Shared by ${row.owner_name||row.owner_email||'staff'} · ${permissionLabel(row.permission)}`:`Saved roster · ${permissionLabel(row.permission)}`;return special?`${base} · ${special}`:base;}
  function rosterCard(row,section){const key=keyOf(row),checked=state.selected.has(key),shared=section==='shared'||section==='hidden';const actions=[`<button type="button" data-view-roster="${esc(key)}">View students</button>`];if(row.can_edit)actions.push(`<button type="button" data-edit-roster="${esc(key)}">Edit</button>`);else if(row.can_suggest)actions.push(`<button type="button" data-suggest-roster="${esc(key)}">Suggest changes</button>`);if(row.can_manage_shares)actions.push(`<button type="button" data-share-roster="${esc(key)}">Sharing & suggestions</button>`);if(shared)actions.push(`<button type="button" data-hide-roster="${esc(key)}" data-hidden="${section==='hidden'?'0':'1'}">${section==='hidden'?'Unhide':'Hide'}</button>`);if(row.can_delete)actions.push(`<button class="danger" type="button" data-delete-roster="${esc(key)}">Delete</button>`);if(section==='legacy')actions.push(`<button class="primary" type="button" data-import-roster="${esc(key)}">Import to My Rosters</button>`);return `<div class="rosterCard" data-card-key="${esc(key)}"><div class="rosterTop"><input type="checkbox" data-select-roster="${esc(key)}" ${checked?'checked':''} aria-label="Select roster"><div class="rosterMain"><div class="rosterName">${esc(row.name||'Roster')}</div><div class="rosterMeta">${esc(metaText(row,section))} · ${Number(row.student_count||0)} student(s)${row.subtitle?` · ${esc(row.subtitle)}`:''}</div><div class="rosterActions">${actions.join('')}</div></div></div><div class="rosterDetails" data-details-for="${esc(key)}"><div class="muted tiny">Load students to view details.</div></div></div>`;}
  function renderCatalogs(){$('customCount').textContent=String(state.owned.length);$('sharedCount').textContent=String(state.shared.length);$('hiddenCount').textContent=String(state.hidden.length);$('customRosters').innerHTML=state.owned.length?state.owned.map(r=>rosterCard(r,'owned')).join(''):'<div class="empty">No custom rosters yet. Build one on the right.</div>';$('sharedRosters').innerHTML=state.shared.length?state.shared.map(r=>rosterCard(r,'shared')).join(''):'<div class="empty">No rosters have been shared with you.</div>';$('hiddenSharedCard').hidden=!state.hidden.length;$('hiddenSharedRosters').innerHTML=state.hidden.map(r=>rosterCard(r,'hidden')).join('');$('systemRosters').innerHTML=state.system.length?state.system.map(r=>rosterCard(r,'system')).join(''):'<div class="empty">No current class/advisory rosters are mapped to this account.</div>';$('legacyCard').hidden=!state.legacy.length;$('legacyRosters').innerHTML=state.legacy.map(r=>rosterCard(r,'legacy')).join('');updateSelectedToolbar();}
  async function refresh(){const data=await api('/admin/my_rosters',{method:'GET'});state.owned=Array.isArray(data.custom_rosters)?data.custom_rosters:[];state.shared=Array.isArray(data.shared_rosters)?data.shared_rosters:[];state.hidden=Array.isArray(data.hidden_shared_rosters)?data.hidden_shared_rosters:[];state.system=Array.isArray(data.system_rosters)?data.system_rosters:[];state.legacy=Array.isArray(data.legacy_rosters)?data.legacy_rosters:[];state.staff=Array.isArray(data.shareable_staff)?data.shareable_staff:[];state.locations=Array.isArray(data.special_action_locations)?data.special_action_locations:[];renderSpecialActionLocations();const valid=new Set(allCatalog().map(keyOf));for(const key of [...state.selected.keys()])if(!valid.has(key))state.selected.delete(key);renderCatalogs();}
  async function detailForKey(key){const {kind,id}=parseKey(key);return api(`/admin/my_rosters/detail?kind=${encodeURIComponent(kind)}&id=${encodeURIComponent(id)}`,{method:'GET'});}
  function suggestionText(s){const c=s.changes||{};const parts=[];if((c.add_osis||[]).length)parts.push(`+${c.add_osis.length} add`);if((c.remove_osis||[]).length)parts.push(`−${c.remove_osis.length} remove`);if(c.proposed_name)parts.push(`rename to “${c.proposed_name}”`);return parts.join(' · ')||'No changes';}
  function collaborationHtml(data,row,key){let html='';if(row.can_manage_shares){const opts=state.staff.map(s=>`<option value="${esc(s.email)}">${esc(s.name)} — ${esc(s.email)}</option>`).join('');html+=`<div class="collabBox"><b>Sharing</b><div class="muted tiny">Roster Admins can edit students and manage sharing. Only the owner can delete the roster.</div><div class="row" style="margin-top:7px"><input class="shareEmail" data-share-email-for="${esc(key)}" list="shareStaff-${esc(row.id)}" placeholder="staff email" style="flex:1;min-width:230px"><datalist id="shareStaff-${esc(row.id)}">${opts}</datalist><select data-share-perm-for="${esc(key)}"><option value="view">Viewer</option><option value="suggest">Suggester</option><option value="edit">Editor</option><option value="admin">Roster Admin</option></select><button type="button" data-add-share="${esc(key)}">Add / update access</button></div><div class="shareList">${(data.shares||[]).map(s=>`<div class="shareRow"><span class="grow"><b>${esc(s.staff_email)}</b>${Number(s.hidden)===1?' <span class="pill">hidden by recipient</span>':''}</span><select data-existing-share-perm="${esc(key)}" data-staff-email="${esc(s.staff_email)}"><option value="view" ${s.permission==='view'?'selected':''}>Viewer</option><option value="suggest" ${s.permission==='suggest'?'selected':''}>Suggester</option><option value="edit" ${s.permission==='edit'?'selected':''}>Editor</option><option value="admin" ${s.permission==='admin'?'selected':''}>Roster Admin</option></select><button type="button" data-update-share="${esc(key)}" data-staff-email="${esc(s.staff_email)}">Update</button><button class="danger" type="button" data-remove-share="${esc(key)}" data-staff-email="${esc(s.staff_email)}">Remove</button></div>`).join('')||'<div class="muted tiny" style="margin-top:6px">Not shared yet.</div>'}</div></div>`;}
    if((data.suggestions||[]).length){html+=`<div class="collabBox"><b>Suggestions</b>${data.suggestions.map(s=>`<div class="suggestRow"><div class="grow"><b>${esc(s.proposed_by)}</b> · ${esc(s.status)} · ${esc(suggestionText(s))}${s.note?`<div class="tiny muted">${esc(s.note)}</div>`:''}</div>${row.can_manage_shares&&s.status==='pending'?`<button type="button" data-review-suggestion="${esc(key)}" data-suggestion-id="${esc(s.suggestion_id)}" data-decision="accept">Accept</button><button class="danger" type="button" data-review-suggestion="${esc(key)}" data-suggestion-id="${esc(s.suggestion_id)}" data-decision="reject">Reject</button>`:''}</div>`).join('')}</div>`;}
    if((data.audit||[]).length){html+=`<details class="collabBox"><summary><b>Recent activity</b></summary><div class="auditList">${data.audit.map(a=>`<div class="tiny"><span class="mono">${esc(new Date(a.created_at_iso).toLocaleString())}</span> · <b>${esc(a.actor_email)}</b> · ${esc(a.action)}</div>`).join('')}</div></details>`;}return html;}
  async function viewRoster(key,forceOpen=false){const card=document.querySelector(`[data-card-key="${CSS.escape(key)}"]`);if(!card)return;if(card.classList.contains('open')&&!forceOpen){card.classList.remove('open');return;}card.classList.add('open');const details=card.querySelector('.rosterDetails');details.innerHTML='<div class="muted tiny">Loading students…</div>';try{const data=await detailForKey(key),rows=data.students||[],row=findRow(key)||data.roster;details.innerHTML=`<div class="row tiny muted" style="margin-bottom:6px"><span>${rows.length} current students</span>${data.missing_osis?.length?`<span>· ${data.missing_osis.length} no longer active</span>`:''}</div><div class="scroll"><table><thead><tr><th>Name</th><th>Email</th><th>OSIS</th><th>Grade</th></tr></thead><tbody>${rows.map(s=>studentRowHtml(s,false)).join('')}</tbody></table></div>${collaborationHtml(data,row,key)}`;}catch(e){details.textContent=e.message;}}
  async function loadBuilder(key,mode){try{const data=await detailForKey(key),row=data.roster;state.builder.clear();addStudents(data.students||[]);state.builderMode=mode;state.builderBase={...row,baseline_osis:(data.students||[]).map(x=>x.osis)};$('rosterId').value=String(row?.id||'');$('rosterVersion').value=String(row?.version||'');$('rosterName').value=String(row?.name||'');$('specialActionType').value=String(row?.special_action_type||'');$('specialActionHomeRoom').value=String(row?.special_action_home_room||'');renderSpecialActionUi();$('builderTitle').textContent=`${mode==='suggest'?'Suggest changes':'Edit roster'} — ${row?.name||''}`;$('saveRosterBtn').textContent=mode==='suggest'?'Submit suggestion':'Save changes';$('suggestionNoteWrap').hidden=mode!=='suggest';setStatus(data.missing_osis?.length?`Loaded current students. ${data.missing_osis.length} saved OSIS no longer appear in the active roster.`:mode==='suggest'?'Make your proposed changes below. The roster will not change until an owner/admin accepts them.':'Loaded roster for editing.',true);window.scrollTo({top:0,behavior:'smooth'});}catch(e){setStatus(e.message,false);}}
  async function deleteRoster(key){const row=findRow(key);if(!row?.can_delete)return;if(!confirm(`Delete roster “${row.name}”? This also removes shares and pending suggestions.`))return;try{await api('/admin/my_rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'delete',id:row.id})});if($('rosterId').value===row.id)clearBuilder();state.selected.delete(key);await refresh();setStatus(`Deleted “${row.name}”.`,true);}catch(e){setStatus(e.message,false);}}
  async function importLegacy(key){const row=findRow(key);if(!row||row.kind!=='legacy')return;try{const data=await api('/admin/my_rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'import_legacy',id:row.id})});await refresh();setStatus(`Imported “${data.roster?.name||row.name}” into My Rosters.`,true);}catch(e){setStatus(e.message,false);}}
  async function saveBuilder(){const name=$('rosterName').value.trim(),students=[...state.builder.keys()];if(!name)return setStatus('Name the roster before saving.',false);if(!students.length)return setStatus('Add at least one student first.',false);try{if(state.builderMode==='suggest'){const data=await api('/admin/my_rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'suggest',id:$('rosterId').value,name,osis_list:students,note:$('suggestionNote').value.trim()})});clearBuilder();await refresh();setStatus(`Suggestion submitted (${suggestionText(data.suggestion)}).`,true);return;}const payload={action:'save',id:$('rosterId').value||undefined,name,osis_list:students,special_action_type:$('specialActionType').value||'',special_action_home_room:$('specialActionHomeRoom').value.trim()};if($('rosterVersion').value)payload.version=Number($('rosterVersion').value);const data=await api('/admin/my_rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});$('rosterId').value=String(data.roster?.id||'');$('rosterVersion').value=String(data.roster?.version||'');state.builderMode='edit';$('builderTitle').textContent=`Edit roster — ${data.roster?.name||name}`;$('saveRosterBtn').textContent='Save changes';await refresh();setStatus(`${data.updated?'Updated':'Saved'} “${data.roster?.name||name}” with ${data.roster?.student_count||students.length} student(s).`,true);}catch(e){if(e.data?.error==='roster_changed_reload')setStatus('Someone else changed this roster. Reload it before saving so you do not overwrite their work.',false);else if(e.data?.missing_osis?.length)setStatus(`Cannot save because these OSIS numbers are no longer active: ${e.data.missing_osis.join(', ')}`,false);else setStatus(e.message,false);}}
  async function aggregateSelected(){const items=[...state.selected.keys()].map(parseKey);if(!items.length)return null;return api('/admin/my_rosters/aggregate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({items})});}
  async function updateSelectedToolbar(){const n=state.selected.size;$('selectedRosterCount').textContent=String(n);for(const id of ['copySelectedEmails','copySelectedOsisColumn','copySelectedOsisComma','clearRosterSelection'])$(id).disabled=!n;if(!n){$('selectedStudentCount').textContent='0';return;}$('selectedStudentCount').textContent='…';try{const data=await aggregateSelected();if(state.selected.size===n)$('selectedStudentCount').textContent=String(data?.unique_student_count||0);}catch{$('selectedStudentCount').textContent='?';}}
  async function copySelected(kind){try{const data=await aggregateSelected();if(!data)return;const text=kind==='emails'?(data.emails||[]).join(', '):kind==='column'?(data.osis_list||[]).join('\n'):(data.osis_list||[]).join(', ');await copy(text,kind==='emails'?`${data.emails?.length||0} email addresses`:`${data.osis_list?.length||0} OSIS numbers`);}catch(e){setStatus(e.message,false);}}
  function copyBuilder(kind){const rows=[...state.builder.values()].sort((a,b)=>String(a.name).localeCompare(String(b.name)));const text=kind==='emails'?rows.map(x=>x.email).filter(Boolean).join(', '):kind==='column'?rows.map(x=>x.osis).join('\n'):rows.map(x=>x.osis).join(', ');copy(text,kind==='emails'?`${rows.filter(x=>x.email).length} email addresses`:`${rows.length} OSIS numbers`);}
  async function setHidden(key,hidden){const row=findRow(key);if(!row)return;try{await api('/admin/my_rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'set_hidden',id:row.id,hidden})});state.selected.delete(key);await refresh();setStatus(hidden?`Hidden “${row.name}” from Shared with me.`:`Restored “${row.name}”.`,true);}catch(e){setStatus(e.message,false);}}
  async function shareAction(key,mode,staffEmail='',perm=''){const row=findRow(key);if(!row)return;try{const body={action:mode,id:row.id};if(staffEmail)body.staff_email=staffEmail;if(perm)body.permission=perm;await api('/admin/my_rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});await refresh();await viewRoster(key,true);setStatus(mode==='remove_share'?`Removed access for ${staffEmail}.`:`Updated ${staffEmail} to ${permissionLabel(perm)}.`,true);}catch(e){setStatus(e.message,false);}}
  async function reviewSuggestion(key,suggestionId,decision){try{const row=findRow(key);await api('/admin/my_rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'review_suggestion',id:row.id,suggestion_id:suggestionId,decision})});await refresh();await viewRoster(key,true);setStatus(`${decision==='accept'?'Accepted':'Rejected'} suggestion.`,true);}catch(e){setStatus(e.message,false);}}
  function wire(){
    $('specialActionType').addEventListener('change',renderSpecialActionUi);$('specialActionHomeRoom').addEventListener('input',renderSpecialActionUi);$('addPastedBtn').addEventListener('click',addPasted);$('studentSearch').addEventListener('input',()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(search,180);});
    $('searchResults').addEventListener('click',e=>{const b=e.target.closest('[data-add-search]');if(!b)return;addStudents([{osis:b.dataset.addSearch,name:b.dataset.name,email:b.dataset.email,grade:b.dataset.grade}]);search();});
    $('builderBody').addEventListener('click',e=>{const b=e.target.closest('[data-remove-osis]');if(!b)return;state.builder.delete(String(b.dataset.removeOsis));renderBuilder();});
    $('saveRosterBtn').addEventListener('click',saveBuilder);$('clearBuilderBtn').addEventListener('click',clearBuilder);$('copyBuilderEmails').addEventListener('click',()=>copyBuilder('emails'));$('copyBuilderOsisColumn').addEventListener('click',()=>copyBuilder('column'));$('copyBuilderOsisComma').addEventListener('click',()=>copyBuilder('comma'));
    document.addEventListener('click',e=>{const v=e.target.closest('[data-view-roster]');if(v)return void viewRoster(v.dataset.viewRoster);const ed=e.target.closest('[data-edit-roster]');if(ed)return void loadBuilder(ed.dataset.editRoster,'edit');const sg=e.target.closest('[data-suggest-roster]');if(sg)return void loadBuilder(sg.dataset.suggestRoster,'suggest');const d=e.target.closest('[data-delete-roster]');if(d)return void deleteRoster(d.dataset.deleteRoster);const imp=e.target.closest('[data-import-roster]');if(imp)return void importLegacy(imp.dataset.importRoster);const h=e.target.closest('[data-hide-roster]');if(h)return void setHidden(h.dataset.hideRoster,h.dataset.hidden==='1');const sh=e.target.closest('[data-share-roster]');if(sh)return void viewRoster(sh.dataset.shareRoster,true);const add=e.target.closest('[data-add-share]');if(add){const key=add.dataset.addShare,card=document.querySelector(`[data-card-key="${CSS.escape(key)}"]`),email=card?.querySelector('[data-share-email-for]')?.value?.trim(),perm=card?.querySelector('[data-share-perm-for]')?.value;return void shareAction(key,'share',email,perm);}const up=e.target.closest('[data-update-share]');if(up){const key=up.dataset.updateShare,email=up.dataset.staffEmail,card=document.querySelector(`[data-card-key="${CSS.escape(key)}"]`),sel=[...card.querySelectorAll('[data-existing-share-perm]')].find(x=>x.dataset.staffEmail===email);return void shareAction(key,'share',email,sel?.value||'view');}const rm=e.target.closest('[data-remove-share]');if(rm)return void shareAction(rm.dataset.removeShare,'remove_share',rm.dataset.staffEmail);const rv=e.target.closest('[data-review-suggestion]');if(rv)return void reviewSuggestion(rv.dataset.reviewSuggestion,rv.dataset.suggestionId,rv.dataset.decision);});
    document.addEventListener('change',e=>{const cb=e.target.closest('[data-select-roster]');if(!cb)return;const key=cb.dataset.selectRoster;if(cb.checked)state.selected.set(key,true);else state.selected.delete(key);updateSelectedToolbar();});
    $('copySelectedEmails').addEventListener('click',()=>copySelected('emails'));$('copySelectedOsisColumn').addEventListener('click',()=>copySelected('column'));$('copySelectedOsisComma').addEventListener('click',()=>copySelected('comma'));$('clearRosterSelection').addEventListener('click',()=>{state.selected.clear();renderCatalogs();});
  }
  async function init(){wire();renderBuilder();try{const access=await api('/admin/access',{method:'GET'});if(access?.can?.my_rosters!==true)throw new Error('My Rosters access is not enabled for this account.');$('app').hidden=false;await refresh();}catch(e){$('authCard').hidden=false;$('authCard').textContent=e.message||'Staff sign-in required.';}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
