(() => {
  'use strict';
  // EAGLENEST_MY_ROSTERS_V1_REFLECTION_CONSUMER
  // Reflection Hold may USE a saved/system roster as a starting selection, but
  // it never creates, edits, or deletes the source roster.
  const API_BASE=(()=>{const m=document.querySelector('meta[name="api-base"]');const raw=(m?.content||location.origin).trim();try{return new URL(raw).toString().replace(/\/+$/,'/')||location.origin+'/';}catch{return location.origin+'/';}})();
  const KEYS=['reflection_hold_admin_session_v1','my_rosters_admin_session_v1','ss_admin_session_sid_v1','teacher_att_admin_session_v1','admin_session_v1','admin_session_sid'];
  let catalog=[];
  function sid(){try{for(const k of KEYS){const v=String(sessionStorage.getItem(k)||localStorage.getItem(k)||'').trim();if(v)return v;}}catch{}return '';}
  async function adminFetch(path,init={}){const h=new Headers(init.headers||{}),s=sid();if(s)h.set('x-admin-session',s);return fetch(new URL(path,API_BASE),{...init,headers:h,credentials:'include',cache:'no-store'});}
  function status(msg,ok=true){const el=document.getElementById('resultBox');if(!el)return;el.className=`status ${ok?'ok':'bad'}`;el.textContent=String(msg||'');}
  function keyOf(r){return `${r.kind}|${r.id}`;}
  function selected(){const key=String(document.getElementById('savedRosterSelect')?.value||'');return catalog.find(r=>keyOf(r)===key)||null;}
  function render(){const sel=document.getElementById('savedRosterSelect');if(!sel)return;const current=sel.value;sel.innerHTML='<option value="">Select a roster…</option>';const groups=[['My saved rosters',catalog.filter(x=>x.kind==='custom')],['Current class / advisory rosters',catalog.filter(x=>x.kind==='system')],['Previous saved rosters',catalog.filter(x=>x.kind==='legacy')]];for(const [label,rows] of groups){if(!rows.length)continue;const group=document.createElement('optgroup');group.label=label;for(const r of rows){const o=document.createElement('option');o.value=keyOf(r);o.textContent=`${r.name} (${Number(r.student_count||0)})`;group.appendChild(o);}sel.appendChild(group);}if(current&&catalog.some(r=>keyOf(r)===current))sel.value=current;document.getElementById('loadSavedRosterBtn').disabled=!sel.value;}
  async function refresh(){const r=await adminFetch('/admin/my_rosters',{method:'GET'}),j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.error||`My Rosters HTTP ${r.status}`);catalog=[...(j.custom_rosters||[]),...(j.system_rosters||[]),...(j.legacy_rosters||[])];render();}
  function applyOsis(list){const search=document.getElementById('rosterSearch');if(search&&search.value){search.value='';search.dispatchEvent(new Event('input',{bubbles:true}));}const wanted=new Set((list||[]).map(String)),rows=[...document.querySelectorAll('#rosterBody tr')];let matched=0;for(const row of rows){const cb=row.querySelector('input[type="checkbox"]'),cells=row.querySelectorAll('td'),osis=String(cells?.[2]?.textContent||'').trim();if(!cb||!osis)continue;const on=wanted.has(osis);if(on)matched++;if(cb.checked!==on){cb.checked=on;cb.dispatchEvent(new Event('change',{bubbles:true}));}}return matched;}
  async function load(){const roster=selected();if(!roster)return;status('Loading roster into this Reflection Hold…',true);try{const r=await adminFetch(`/admin/my_rosters/detail?kind=${encodeURIComponent(roster.kind)}&id=${encodeURIComponent(roster.id)}&context=reflection_hold`,{method:'GET'}),j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.error||`Roster load HTTP ${r.status}`);const matched=applyOsis((j.students||[]).map(x=>x.osis));const c=j.context_counts||{};const filtered=[];if(Number(c.not_present_today||0))filtered.push(`${c.not_present_today} not present today`);if(Number(c.left_early||0))filtered.push(`${c.left_early} left early`);if(Number(c.off_campus||0))filtered.push(`${c.off_campus} already off campus`);if(Number(c.not_in_current_roster||0))filtered.push(`${c.not_in_current_roster} no longer in the active roster`);status(`Loaded ${matched} student(s) from “${j.roster?.name||roster.name}” into this Reflection Hold.${filtered.length?` Filtered out: ${filtered.join(', ')}.`:''} You may add/remove students for this hold only; the saved roster will not change.`,true);}catch(e){status(e.message,false);}}
  function install(){const holdLabel=document.getElementById('holdLabel'),holdRow=holdLabel?.closest('.row');if(holdRow&&!document.getElementById('savedRosterSelect')){const wrap=document.createElement('div');wrap.innerHTML=`<div class="row" id="savedRosterControls" style="margin-top:10px;align-items:flex-end;"><div class="grow"><label for="savedRosterSelect">Start from a roster <span class="muted">(optional)</span></label><select id="savedRosterSelect"><option value="">Loading rosters…</option></select></div><button id="loadSavedRosterBtn" type="button" disabled>Load into this hold</button><a href="./my_rosters.html" style="align-self:center;color:inherit">Manage My Rosters</a></div><div class="muted" style="margin-top:6px;">Loading a roster only seeds this Reflection Hold selection. Add/remove students here freely; the source roster can only be changed from My Rosters.</div>`;while(wrap.firstChild)holdRow.parentNode.insertBefore(wrap.firstChild,holdRow);}document.getElementById('savedRosterSelect')?.addEventListener('change',render);document.getElementById('loadSavedRosterBtn')?.addEventListener('click',load);refresh().catch(()=>render());}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
