/* EAGLENEST_GRANDSTREAM_PHASE3_2 — admin campus routing editor */
(() => {
  'use strict';
  const API_BASE=((document.querySelector('meta[name="api-base"]')?.content||location.origin).replace(/\/*$/,'')+'/');
  const HEADER='x-admin-session';
  const KEYS=['ss_admin_session_sid_v1','admin_session_v1','teacher_att_admin_session_v1','staff_pull_admin_session_v1','phone_pass_admin_session_v1','student_scans_admin_session_v1'];
  let access=null,data=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function sid(){try{for(const k of KEYS){const v=String(sessionStorage.getItem(k)||localStorage.getItem(k)||'').trim();if(v)return v;}}catch{}return'';}
  async function api(path,init={}){const h=new Headers(init.headers||{}),s=sid();if(s&&!h.has(HEADER))h.set(HEADER,s);return fetch(new URL(path,API_BASE),{...init,headers:h,credentials:'include',cache:'no-store'});}
  function admin(){const r=String(access?.role||'').toLowerCase();return(r==='admin'||r==='super_admin')&&access?.view_as?.active!==true&&access?.view_as?.read_only!==true;}
  async function loadAccess(){if(access)return access;try{const r=await api('/admin/access'),j=await r.json();access=r.ok&&j?.ok?j:null;}catch{access=null;}return access;}
  function style(){if(document.getElementById('campusRoutingStyle'))return;const s=document.createElement('style');s.id='campusRoutingStyle';s.textContent=`
#campusRoutingDialog{width:min(860px,calc(100vw - 28px));max-height:84vh;overflow:auto;border:1px solid var(--border,rgba(148,163,184,.3));border-radius:18px;background:var(--panel,#0f172a);color:var(--fg,#e5e7eb);padding:0;box-shadow:0 30px 80px rgba(0,0,0,.38)}#campusRoutingDialog::backdrop{background:rgba(2,6,23,.62);backdrop-filter:blur(2px)}.crHead{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;padding:18px;border-bottom:1px solid var(--border,rgba(148,163,184,.24))}.crBody{padding:18px}.crFoot{display:flex;justify-content:flex-end;gap:8px;padding:14px 18px;border-top:1px solid var(--border,rgba(148,163,184,.24));position:sticky;bottom:0;background:var(--panel,#0f172a)}.crSection{margin-top:18px}.crSection h3{margin:0 0 8px}.crHelp{font-size:12px;color:var(--muted,#94a3b8);line-height:1.45}.crRows{display:grid;gap:7px}.crRow{display:grid;grid-template-columns:minmax(180px,1fr) 82px minmax(150px,220px);gap:8px;align-items:center;padding:8px;border:1px solid var(--border,rgba(148,163,184,.2));border-radius:11px}.crValue{overflow-wrap:anywhere;font:12px ui-monospace,SFMono-Regular,Menlo,monospace}.crCount{font-size:11px;color:var(--muted,#94a3b8)}.crRow select,.crInput,.crText{width:100%;border:1px solid var(--border,rgba(148,163,184,.3));background:var(--control,rgba(2,6,23,.32));color:inherit;border-radius:9px;padding:8px;font:inherit}.crText{min-height:92px;resize:vertical;font:12px ui-monospace,SFMono-Regular,Menlo,monospace}.crError{color:var(--bad,#fca5a5);font-size:12px;margin-top:10px}.crGood{color:var(--good,#86efac)}@media(max-width:680px){.crRow{grid-template-columns:1fr}.crCount{display:none}}`;document.head.appendChild(s);}
  function opts(campuses,selected=''){return['<option value="">Unassigned</option>',...campuses.map(c=>`<option value="${esc(c)}"${c===selected?' selected':''}>${esc(c)}</option>`)].join('');}
  function rows(type){const d=Array.isArray(data?.discovered?.[type])?data.discovered[type]:[],m=data?.config?.mappings?.[type]||{},by=new Map(d.map(x=>[String(x.value||'').toLowerCase(),x]));for(const k of Object.keys(m))if(!by.has(k.toLowerCase()))by.set(k.toLowerCase(),{value:k,count:0});return[...by.values()];}
  function section(title,type,help){const campuses=data?.config?.campuses||[],m=data?.config?.mappings?.[type]||{},r=rows(type);return`<section class="crSection" data-map-type="${esc(type)}"><h3>${esc(title)}</h3><div class="crHelp">${esc(help)}</div><div class="crRows" style="margin-top:8px">${r.length?r.map(x=>{const k=String(x.value||''),sel=m[k.toLowerCase()]||'';return`<label class="crRow"><span class="crValue">${esc(k)}</span><span class="crCount">${Number(x.count||0)} calls</span><select data-map-key="${esc(k)}">${opts(campuses,sel)}</select></label>`;}).join(''):'<div class="crHelp">Nothing discovered yet. Run Sync PBX after this update to backfill routing metadata.</div>'}</div></section>`;}
  function prefixText(){return Object.entries(data?.config?.mappings?.extension_prefix||{}).map(([p,c])=>`${p}=${c}`).join('\n');}
  function render(){style();let d=document.getElementById('campusRoutingDialog');if(!d){d=document.createElement('dialog');d.id='campusRoutingDialog';document.body.appendChild(d);}const cs=data?.config?.campuses||['High School','Middle School'];d.innerHTML=`<div class="crHead"><div><h2 style="margin:0">Campus Call Routing</h2><div class="crHelp" style="margin-top:5px">Map Grandstream routing metadata to a campus. Changes affect both live caller cards and historical calls.</div></div><button class="btn secondary small" data-close>Close</button></div><div class="crBody"><label><strong>Campus labels</strong><div class="crHelp">Comma-separated.</div><input id="crCampuses" class="crInput" value="${esc(cs.join(', '))}" style="margin-top:6px"></label>${section('Inbound trunks','source_trunk','Best incoming-call signal when each campus uses a different trunk.')}${section('Inbound contexts','context','Historical fallback such as ext-did-* contexts.')}${section('Route targets','route_target','Ring group, queue, or internal destination captured from PBX metadata.')}${section('Outbound trunks','destination_trunk','Optional mapping for outbound traffic.')}<section class="crSection"><h3>Extension-prefix fallback</h3><div class="crHelp">One rule per line as PREFIX=Campus. Longest prefix wins.</div><textarea id="crExtensionPrefixes" class="crText" style="margin-top:8px">${esc(prefixText())}</textarea></section><div class="crHelp" style="margin-top:16px">After deploying Phase 3.2, run <strong>Sync PBX</strong> once to backfill the last 30 days with routing metadata. Campus labels themselves resolve dynamically, so remapping updates old calls immediately.</div><div id="crError" class="crError" aria-live="polite"></div></div><div class="crFoot"><button class="btn secondary" data-close>Cancel</button><button class="btn primary" id="crSave">Save routing</button></div>`;d.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>d.close()));d.querySelector('#crSave')?.addEventListener('click',save);return d;}
  function prefixes(cs){const out={},valid=new Map(cs.map(c=>[c.toLowerCase(),c]));for(const line of String(document.getElementById('crExtensionPrefixes')?.value||'').split(/\r?\n/)){const t=line.trim();if(!t)continue;const i=t.indexOf('=');if(i<1)throw new Error(`Invalid prefix rule: ${t}`);const p=t.slice(0,i).replace(/\D/g,''),c=valid.get(t.slice(i+1).trim().toLowerCase());if(!p||!c)throw new Error(`Invalid prefix rule: ${t}`);out[p]=c;}return out;}
  async function save(){const e=document.getElementById('crError'),b=document.getElementById('crSave');if(e)e.textContent='';if(b)b.disabled=true;try{const cs=String(document.getElementById('crCampuses')?.value||'').split(',').map(v=>v.trim()).filter(Boolean);if(!cs.length)throw new Error('Add at least one campus label.');const mappings={source_trunk:{},destination_trunk:{},context:{},route_target:{},extension_prefix:prefixes(cs)};document.querySelectorAll('#campusRoutingDialog [data-map-type]').forEach(sec=>{const type=sec.getAttribute('data-map-type');sec.querySelectorAll('select[data-map-key]').forEach(s=>{const k=s.getAttribute('data-map-key')?.trim(),c=s.value.trim();if(k&&c)mappings[type][k]=c;});});const r=await api('/admin/integrations/grandstream/campus_routing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({campuses:cs,mappings})}),j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.error||`HTTP ${r.status}`);data={...data,config:j.config};if(e){e.className='crError crGood';e.textContent='Saved. Live campus routing refreshed.';}setTimeout(()=>document.getElementById('campusRoutingDialog')?.close(),700);}catch(err){if(e){e.className='crError';e.textContent=String(err?.message||err);}}finally{if(b)b.disabled=false;}}
  async function open(){const b=document.getElementById('campusRoutingBtn');if(b)b.disabled=true;try{const r=await api('/admin/integrations/grandstream/campus_routing'),j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.error||`HTTP ${r.status}`);data=j;render().showModal();}catch(e){alert(`Could not load campus routing: ${e?.message||e}`);}finally{if(b)b.disabled=false;}}
  function button(){if(!admin()||document.getElementById('campusRoutingBtn'))return;const host=document.querySelector('#panelCalls .inlineActions');if(!host)return;const b=document.createElement('button');b.id='campusRoutingBtn';b.type='button';b.className='btn secondary small';b.textContent='Campus Routing';b.addEventListener('click',open);host.prepend(b);}
  async function init(){await loadAccess();if(!admin())return;for(let i=0;i<40;i++){button();if(document.getElementById('campusRoutingBtn'))return;await new Promise(r=>setTimeout(r,100));}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
